### ISSUE TITLE
Unable to view admin/dashboard : Variable "textFieldSources" does not exist

### ISSUE THREAD

**Issue by Chrisedmo** [nystudio107/craft-seomatic#1002]
### Describe the bug
I am unable to view my dashboard page (admin/dashboard)

### To reproduce
Steps to reproduce the behaviour:
1. Go to "admin/dashboard"
2. See error message "Variable "textFieldSources" does not exist."

### Screenshots
```  
Issue appears to be at line 71 in 'craft-seomatic/src/templates/settings/_includes/fields/_seoTitle.twig'
{% block inheritedValues %}
      This is red  >   {{ _self.seoTitleField(textOptions, textFieldSources, seomatic.config, inheritedFrom.metaBundleSettings ?? metaBundleSettings, inheritedFrom.metaGlobalVars ?? metaGlobalVars, "-inherited") }}
    {% endblock %
}
```

### Versions
- Plugin version: 3.4.16
- Craft version: 3.7.16

**Comment by khalwat** [comment]
Do you have any idea why it might be trying to display the SEO Title field settings on your dashboard page? Something doesn't seem right here?

**Comment by khalwat** [comment]
Can you post a full stack crawl of the error you're seeing please?

**Comment by Chrisedmo** [comment]
Thanks for the quick response, yes that does seem odd!

```
Twig\Error\RuntimeError: Variable "textFieldSources" does not exist. in ~ websitepath ~ /vendor/nystudio107/craft-seomatic/src/templates/settings/_includes/fields/_seoTitle.twig:71
Stack trace:
#0 ~ websitepath ~ /storage/runtime/compiled_templates/ac/accf6a93d0a52e9fd835adafc9382c7e34f5ebee4e9b114c33d5283a22e6ccbb.php(206): __TwigTemplate_e356e82cd980e09b5a29f7cf1e752dfa321ac65a81ac6002f3ecd9d24c583a56___1735841470->{closure}()
#1 ~ websitepath ~ /vendor/twig/twig/src/Template.php(182): __TwigTemplate_e356e82cd980e09b5a29f7cf1e752dfa321ac65a81ac6002f3ecd9d24c583a56___1735841470->block_inheritedValues(Array, Array)
#2 ~ websitepath ~ /storage/runtime/compiled_templates/b9/b953750443ddc4fe8fdde74b6757e702bd9b703b1f90fc8c5e25f426f3e52d02.php(113): Twig\Template->displayBlock('inheritedValues', Array, Array)
#3 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_c1318f092794309c9ca0fcbefe32cd5f756418493409415a9fdba199e06e8704->doDisplay(Array, Array)
#4 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#5 ~ websitepath ~ /storage/runtime/compiled_templates/ac/accf6a93d0a52e9fd835adafc9382c7e34f5ebee4e9b114c33d5283a22e6ccbb.php(195): Twig\Template->display(Array, Array)
#6 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_e356e82cd980e09b5a29f7cf1e752dfa321ac65a81ac6002f3ecd9d24c583a56___1735841470->doDisplay(Array, Array)
#7 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#8 ~ websitepath ~ /storage/runtime/compiled_templates/ac/accf6a93d0a52e9fd835adafc9382c7e34f5ebee4e9b114c33d5283a22e6ccbb.php(51): Twig\Template->display(Array)
#9 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_e356e82cd980e09b5a29f7cf1e752dfa321ac65a81ac6002f3ecd9d24c583a56->doDisplay(Array, Array)
#10 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 ~ websitepath ~ /storage/runtime/compiled_templates/97/97fbeb6c7c1679be0d2de6dd54df0185bf4a69d436f8923b3e82f04a02423281.php(83): Twig\Template->display(Array)
#12 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_bc7375a9ce22e54850e6186ca83d7e4cda1e06516ccd9cf5f0ba807387ad6beb->doDisplay(Array, Array)
#13 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#14 ~ websitepath ~ /storage/runtime/compiled_templates/d4/d470179b7db6572bb39586288f94f1bb9e7896366b71cfd1364f008325631c50.php(164): Twig\Template->display(Array)
#15 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_8a723d6dd0791b361fbd6f3eaa3e73f53a2709397562b51eb4e0452dc54365cd->doDisplay(Array, Array)
#16 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#17 ~ websitepath ~ /vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#18 ~ websitepath ~ /vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#19 ~ websitepath ~ /vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#20 ~ websitepath ~ /vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('seomatic/_compo...', Array)
#21 ~ websitepath ~ /vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php(375): craft\web\View->renderTemplate('seomatic/_compo...', Array)
#22 ~ websitepath ~ /vendor/twig/twig/src/Extension/CoreExtension.php(1511): nystudio107\seomatic\fields\SeoSettings->getInputHtml(Object(nystudio107\seomatic\models\MetaBundle), NULL)
#23 ~ websitepath ~ /vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\fields\SeoSettings), 'getInputHtml', Array, 'method', false, false)
#24 ~ websitepath ~ /storage/runtime/compiled_templates/82/8207f3b0cc82d37944f19245edb4512f99c088102b2d0fcd8fa23da6f9448a2f.php(87): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\fields\SeoSettings), 'getInputHtml', Array, 'method')
#25 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_8859b7f634bcaa4acf92c4f22ac05086efb3149d18ff9d7de6208235b87fb0ff->doDisplay(Array, Array)
#26 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#27 ~ websitepath ~ /storage/runtime/compiled_templates/1d/1db0e068c9e1542629cc79c1dacb12fa972e64cf1d70263402ff60e915e1ac5c.php(91): Twig\Template->display(Array)
#28 ~ websitepath ~ /vendor/twig/twig/src/Template.php(405): __TwigTemplate_43cb9b1b8cec0b0da81c1dc2855c8431e5416f4fb8bb6a10122700e3926d2d87->doDisplay(Array, Array)
#29 ~ websitepath ~ /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#30 ~ websitepath ~ /vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#31 ~ websitepath ~ /vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#32 ~ websitepath ~ /vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#33 ~ websitepath ~ /vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_components/wid...', Array)
#34 ~ websitepath ~ /vendor/craftcms/cms/src/widgets/QuickPost.php(174): craft\web\View->renderTemplate('_components/wid...', Array)
#35 ~ websitepath ~ /vendor/craftcms/cms/src/controllers/DashboardController.php(505): craft\widgets\QuickPost->getBodyHtml()
#36 ~ websitepath ~ /vendor/craftcms/cms/src/controllers/DashboardController.php(105): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\QuickPost))
#37 [internal function]: craft\controllers\DashboardController->actionIndex()
#38 ~ websitepath ~ /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#39 ~ websitepath ~ /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#40 ~ websitepath ~ /vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('index', Array)
#41 ~ websitepath ~ /vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('index', Array)
#42 ~ websitepath ~ /vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('dashboard/index', Array)
#43 ~ websitepath ~ /vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('dashboard/index', Array)
#44 ~ websitepath ~ /vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#45 ~ websitepath ~ /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#46 ~ websitepath ~ /web/index.php(26): yii\base\Application->run()
#47 /Users/chrismousdale/.composer/vendor/laravel/valet/server.php(235): require('/Users/chrismou...')
#48 {main}
```

**Comment by Chrisedmo** [comment]
Ahhh it must be due to a quick post in the dashboard?

**Comment by khalwat** [comment]
Aha! That makes sense. Let me have a look.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/2f9a3c6413da4e965a3332f465bdc92756d4d4b6

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.17”,
```
Then do a `composer clear-cache && composer update`
