### ISSUE TITLE
Error upating to 3.4.24

### ISSUE THREAD

**Issue by AndrewMac** [nystudio107/craft-seomatic#1062]
### Describe the bug
I just ran composer update to move to Seomatic 3.4.24. In my composer.json are three scripts that perform additional tasks, and all of these three scripts return the same error (below):

> @php craft install/check && php craft up || return 0
Exception 'Error' with message 'Undefined class constant 'EVENT_AFTER_SAVE_PRODUCTTYPES''

```
in /app/vendor/nystudio107/craft-seomatic/src/seoelements/SeoDigitalProduct.php:108

Stack trace:
#0 /app/vendor/nystudio107/craft-seomatic/src/services/SeoElements.php(118): nystudio107\seomatic\seoelements\SeoDigitalProduct::installEventHandlers()
#1 /app/vendor/nystudio107/craft-seomatic/src/Seomatic.php(477): nystudio107\seomatic\services\SeoElements->getAllSeoElementTypes(false)
#2 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#3 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#4 /app/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#5 /app/vendor/craftcms/cms/src/services/Plugins.php(278): yii\base\Component->trigger('afterLoadPlugin...')
#6 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#7 /app/vendor/craftcms/cms/src/console/Application.php(48): craft\console\Application->_postInit()
#8 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#9 /app/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#10 /app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#11 [internal function]: yii\console\Application->__construct(Array)
#12 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#13 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#14 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#15 /app/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#16 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(246): Craft::createObject(Array)
#17 /app/vendor/craftcms/cms/bootstrap/console.php(51): require('/app/vendor/cra...')
#18 /app/craft(26): require('/app/vendor/cra...')
#19 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. Perform composer update with additional scripts
2. See the error message listed above

### Expected behaviour
Scripts perform as they should.

### Versions
- Plugin version: 3.2.23 -> 3.2.24
- Craft version: 3.7.23 Pro
- Nitro version 2.0.8

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/57b8b2c7f58f104b0829e29c87d8a9f5f4f8f673

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.25”,
```
Then do a `composer clear-cache && composer update`

**Comment by AndrewMac** [comment]
Thank you!
