### ISSUE TITLE
Calling unknown method Request::getFullPath()

### ISSUE THREAD

**Issue by PhilReinking** [nystudio107/craft-seomatic#1080]
### Describe the bug
I get a `Calling unknown method` error when trying to update my search index via Scout. We have a custom Transformer class that does a GraphQL request including seomatic fields. If I remove them, or if they are cached, it works as expected. 

Changing line 104 in the FrontendTemplates class seems to fix the issue:
`$fullPath = $request->isConsoleRequest ? '' : $request->getFullPath();`

I attach the stack trace we get:

```
yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getFullPath() in /home/site/wwwroot/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/services/FrontendTemplates.php(104): yii\base\Component->__call('getFullPath', Array)
#1 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(430): nystudio107\seomatic\services\FrontendTemplates->loadFrontendTemplateContainers(1)
#2 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(320): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('routine/heart-o...', 1)
#3 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/helpers/Container.php(96): nystudio107\seomatic\services\MetaContainers->previewMetaContainers('routine/heart-o...', 1, true)
#4 [internal function]: nystudio107\seomatic\helpers\Container::nystudio107\seomatic\helpers\{closure}(Object(craft\cache\FileCache))
#5 /home/site/wwwroot/vendor/yiisoft/yii2/caching/Cache.php(607): call_user_func(Object(Closure), Object(craft\cache\FileCache))
#6 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/helpers/Container.php(87): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 30, Object(yii\caching\TagDependency))
#7 /home/site/wwwroot/vendor/nystudio107/craft-seomatic/src/gql/resolvers/SeomaticResolver.php(64): nystudio107\seomatic\helpers\Container::getContainerArrays(Array, 'routine/heart-o...', 1, true)
#8 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(623): nystudio107\seomatic\gql\resolvers\SeomaticResolver::resolve(Object(craft\elements\Entry), Array, Array, Object(GraphQL\Type\Definition\ResolveInfo))
#9 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\Executor\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\Type\Definition\FieldDefinition), Object(GraphQL\Language\AST\FieldNode), 'nystudio107\\seo...', Object(craft\elements\Entry), Object(GraphQL\Type\Definition\ResolveInfo))
#10 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\Executor\ReferenceExecutor->resolveField(Object(craft\gql\types\elements\Entry), Object(craft\elements\Entry), Object(ArrayObject), Array)
#11 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\Executor\ReferenceExecutor->executeFields(Object(craft\gql\types\elements\Entry), Object(craft\elements\Entry), Array, Object(ArrayObject))
#12 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\Executor\ReferenceExecutor->collectAndExecuteSubfields(Object(craft\gql\types\elements\Entry), Object(ArrayObject), Array, Object(craft\elements\Entry))
#13 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(974): GraphQL\Executor\ReferenceExecutor->completeObjectValue(Object(craft\gql\types\elements\Entry), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(craft\elements\Entry))
#14 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(789): GraphQL\Executor\ReferenceExecutor->completeAbstractValue(Object(GraphQL\Type\Definition\InterfaceType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(craft\elements\Entry))
#15 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\Executor\ReferenceExecutor->completeValue(Object(GraphQL\Type\Definition\InterfaceType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(craft\elements\Entry))
#16 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\Type\Definition\InterfaceType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(craft\elements\Entry))
#17 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\Executor\ReferenceExecutor->resolveField(Object(GraphQL\Type\Definition\ObjectType), NULL, Object(ArrayObject), Array)
#18 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\Executor\ReferenceExecutor->executeFields(Object(GraphQL\Type\Definition\ObjectType), NULL, Array, Object(ArrayObject))
#19 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\Executor\ReferenceExecutor->executeOperation(Object(GraphQL\Language\AST\OperationDefinitionNode), NULL)
#20 /home/site/wwwroot/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\Executor\ReferenceExecutor->doExecute()
#21 /home/site/wwwroot/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\Executor\Executor::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), Object(GraphQL\Language\AST\DocumentNode), NULL, Array, Array, NULL, NULL)
#22 /home/site/wwwroot/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\GraphQL::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), '\n              ...', NULL, Array, Array, NULL, NULL, Array)
#23 /home/site/wwwroot/vendor/craftcms/cms/src/services/Gql.php(546): GraphQL\GraphQL::executeQuery(Object(GraphQL\Type\Schema), '\n              ...', NULL, Array, Array, NULL, NULL, Array)
#24 /home/site/wwwroot/modules/algoliamodule/src/services/transformers/PageTransformer.php(56): craft\services\Gql->executeQuery(Object(craft\models\GqlSchema), '\n              ...', Array)
#25 /home/site/wwwroot/config/scout.php(53): modules\algoliamodule\services\transformers\PageTransformer->transform(Object(craft\elements\Entry), 'en')
#26 [internal function]: craft\services\Config->{closure}(Object(craft\elements\Entry))
#27 /home/site/wwwroot/vendor/league/fractal/src/Scope.php(416): call_user_func(Object(Closure), Object(craft\elements\Entry))
#28 /home/site/wwwroot/vendor/league/fractal/src/Scope.php(358): League\Fractal\Scope->fireTransformer(Object(Closure), Object(craft\elements\Entry))
#29 /home/site/wwwroot/vendor/league/fractal/src/Scope.php(235): League\Fractal\Scope->executeResourceTransformers()
#30 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/behaviors/SearchableBehavior.php(117): League\Fractal\Scope->toArray()
#31 [internal function]: rias\scout\behaviors\SearchableBehavior->toSearchableArray(Object(rias\scout\ScoutIndex))
#32 /home/site/wwwroot/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array(Array, Array)
#33 /home/site/wwwroot/vendor/craftcms/cms/src/base/Element.php(1797): yii\base\Component->__call('toSearchableArr...', Array)
#34 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/engines/AlgoliaEngine.php(114): craft\base\Element->__call('toSearchableArr...', Array)
#35 [internal function]: rias\scout\engines\AlgoliaEngine->rias\scout\engines\{closure}(Object(craft\elements\Entry), 1)
#36 /home/site/wwwroot/vendor/tightenco/collect/src/Collect/Support/Collection.php(695): array_map(Object(Closure), Array, Array)
#37 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/engines/AlgoliaEngine.php(122): Tightenco\Collect\Support\Collection->map(Object(Closure))
#38 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/engines/AlgoliaEngine.php(44): rias\scout\engines\AlgoliaEngine->transformElements(Object(Tightenco\Collect\Support\Collection))
#39 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/console/controllers/scout/IndexController.php(58): rias\scout\engines\AlgoliaEngine->update(Object(Tightenco\Collect\Support\Collection))
#40 /home/site/wwwroot/vendor/tightenco/collect/src/Collect/Support/Traits/EnumeratesValues.php(244): rias\scout\console\controllers\scout\IndexController->rias\scout\console\controllers\scout\{closure}(Object(rias\scout\engines\AlgoliaEngine), 0)
#41 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/console/controllers/scout/IndexController.php(62): Tightenco\Collect\Support\Collection->each(Object(Closure))
#42 /home/site/wwwroot/vendor/studioespresso/craft-scout/src/console/controllers/scout/IndexController.php(70): rias\scout\console\controllers\scout\IndexController->actionImport('')
#43 [internal function]: rias\scout\console\controllers\scout\IndexController->actionRefresh('')
#44 /home/site/wwwroot/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#45 /home/site/wwwroot/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#46 /home/site/wwwroot/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('refresh', Array)
#47 /home/site/wwwroot/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('refresh', Array)
#48 /home/site/wwwroot/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('refresh', Array)
#49 /home/site/wwwroot/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('scout/index/ref...', Array)
#50 /home/site/wwwroot/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('scout/index/ref...', Array)
#51 /home/site/wwwroot/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('scout/index/ref...', Array)
#52 /home/site/wwwroot/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#53 /home/site/wwwroot/craft(22): yii\base\Application->run()
#54 {main}
```

### Versions
- Plugin version: 3.4.26
- Craft version: 3.7.34

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/9b0fbfee2b86353f56f3c24c48d1b21068a314af

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.28”,
```
Then do a `composer clear-cache && composer update`
