### ISSUE TITLE
Saving SEO data for Category Collection Throws Type Error

### ISSUE THREAD

**Issue by sergeifilippov** [nystudio107/craft-seomatic#124]
I have a Category Group. When trying to save any setting, I get the following `TypeError`

```
TypeError: Argument 1 passed to nystudio107\seomatic\services\MetaBundles::updateMetaBundle() must be an instance of nystudio107\seomatic\models\MetaBundle, null given, called in src/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php on line 552 and defined in src/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php:125
Stack trace:
#0 src/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(552): nystudio107\seomatic\services\MetaBundles->updateMetaBundle(NULL, '1')
#1 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionSaveContent()
#2 src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 src/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 src/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-content', Array)
#5 src/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-content', Array)
#6 src/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('seomatic/settin...', Array)
#7 src/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('seomatic/settin...', Array)
#8 src/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 src/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 src/web/index.php(42): yii\base\Application->run()
#11 {main}
```

System:

- Craft Pro 3.0.9
- php 7.1.18
- MySQL 5.7.21

**Comment by khalwat** [comment]
Does your Category Group have URLs @sergeifilippov ?

**Comment by khalwat** [comment]
I'm unclear on what conditions could cause this to happen, but this should address it: https://github.com/nystudio107/craft-seomatic/commit/82b2fb4e0662d87a0d046b65cc46f506c0593c0b
