### ISSUE TITLE
Craft 5 Update - convert charset error

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#1444]
### Describe the bug
Updating site from Craft 4 to Craft 5 and when I get to [step 11 of the instructions ](https://craftcms.com/docs/5.x/upgrade.html) and run the command `php craft db/convert-charset` it fails.
I assume this is an SEOmatic issue because it fails on the `craft_seomatic_settings` table.

### To reproduce
Steps to reproduce the behaviour:
1. Follow upgrade instructions for Craft 4 to 5
2. get to step 11 and run this command `php craft db/convert-charset`
3. See error message this error in the CLI
```
Converting craft_seomatic_settings ... Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access 
violation: 1118 Row size too large. The maximum row size for 
the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
The SQL being executed was: ALTER TABLE `craft_seomatic_settings` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci'

in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676       

Error Info:
Array
(
    [0] => 42000
    [1] => 1118
    [2] => Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the 
manual. You have to change some columns to TEXT or BLOBs'    

in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1302     

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `cr...')
#2 /var/www/html/vendor/craftcms/cms/src/console/controllers/DbController.php(366): yii\db\Command->execute()
#3 [internal function]: craft\console\controllers\DbController->actionConvertCharset('utf8mb4', 'utf8mb4_0900_ai...')     
#4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('convert-charset', Array)#7 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('convert-charset', Array)
#8 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('convert-charset', Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('convert-charset', Array)  
#10 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('db/convert-char...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('db/convert-char...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('db/convert-char...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/html/craft(13): yii\base\Application->run()     
#16 {main}
```

### Expected behaviour
Converting charsets completes successfully

### Versions
- Plugin version:
- Craft version:

**Comment by khalwat** [comment]
Is this a very old site? That table isn't used by SEOmatic anymore, it's probably just a relic from the Craft 2 version of SEOmatic perhaps? Just delete the table.

**Comment by CreateSean** [comment]
Thanks that got me past that step,, now another issue to deal with, but not SEOmatic related.
