### ISSUE TITLE
Cache exception when setting seoImage

### ISSUE THREAD

**Issue by lexisother** [nystudio107/craft-seomatic#1545]
### Describe the bug
I am trying to set a Craft asset as the `seoImage` in my template, but I am getting the below exception. I am not entirely sure why this is happening, since for the past four years this has functioned fine, but it appears this started happening after the Craft 5 update.
```
Exception: Serialization of 'Closure' is not allowed in /var/www/html/vendor/yiisoft/yii2/caching/Cache.php:249
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(249): serialize(Array)
#1 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(609): yii\caching\Cache->set('parsed_globals_...', Array, 30, Object(yii\caching\TagDependency))
#2 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(253): yii\caching\Cache->getOrSet('parsed_globals_...', Object(Closure), 30, Object(yii\caching\TagDependency))
#3 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(232): nystudio107\seomatic\services\MetaContainers->parseGlobalVars()
#4 /var/www/html/vendor/nystudio107/craft-seomatic/src/Seomatic.php(745): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#5 [internal function]: nystudio107\seomatic\Seomatic::nystudio107\seomatic\{closure}(Object(yii\base\Event))
#6 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#7 /var/www/html/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#8 /var/www/html/vendor/yiisoft/yii2/web/View.php(187): yii\base\Component->trigger('endPage')
#9 /var/www/html/vendor/craftcms/cms/src/web/View.php(1943): yii\web\View->endPage(false)
#10 /var/www/html/vendor/yiisoft/yii2/views/errorHandler/exception.php(544): craft\web\View->endPage()
#11 /var/www/html/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/v...')
#12 /var/www/html/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile('/var/www/html/v...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/var/www/html/v...', Array, Object(craft\web\ErrorHandler))
#14 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(190): yii\web\ErrorHandler->renderException(Object(Exception))
#16 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(Exception))
#17 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(66): yii\base\ErrorHandler->handleException(Object(Exception))
#18 [internal function]: craft\web\ErrorHandler->handleException(Object(Exception))
#19 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. Fetch an Asset within a Twig template
2. Run `{% do seomatic.meta.seoImage(yourAsset) %}`

### Expected behaviour
I expect it to work/set the `seoImage`/not throw an exception.

### Screenshots
<img width="1538" alt="image" src="https://github.com/user-attachments/assets/cc5ce8a7-91ec-4fe4-b21d-736f86c188ac">

### Versions
- Plugin version: 5.1.5
- Craft version: 5.4.9

**Comment by khalwat** [comment]
So you should be doing:

```twig
{% do seomatic.meta.seoImage(yourAsset.getUrl()) %}
```
... as it expects a string, not an asset.
