### ISSUE TITLE
`Impossible to invoke a method ("hreflang") on a null variable.`

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#202]
So, I'm using Craft 3.0.20 with SEOmatic 3.1.14.

I'm getting this template error thrown when I run a search

```
Twig_Error_Runtime: Impossible to invoke a method ("hreflang") on a null variable. in C:\Users\xmr\Desktop\foobar\templates\_layout.twig:10
Stack trace:
#0 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\helpers\Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), NULL, 'hreflang', Array, 'method', false, false)
#1 C:\Users\xmr\Desktop\foobar\storage\runtime\compiled_templates\98\988ef2e168a402725ff8b14419bb311abff92db99daed6ce4a2570d0ae0b7215.php(43): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), NULL, 'hreflang', Array, 'method')
#2 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_907806db2f88929e121061ce94211e9a3d103406548209027e48886c36ed4f68->doDisplay(Array, Array)
#3 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#4 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#5 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#6 C:\Users\xmr\Desktop\foobar\storage\runtime\compiled_templates\cc\ccea36431365ed5b7a43fd5699c828e1b75935038ae28f5691b564d34482a8cc.php(31): craft\web\twig\Template->display(Array, Array)
#7 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Template.php(390): __TwigTemplate_4c60f2d58c7235be68628af224a7cdf7a407eb869a7b1c43b48f1b1d4fb30268->doDisplay(Array, Array)
#8 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\twig\Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#9 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#10 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\twig\Template.php(31): Twig_Template->display(Array, Array)
#11 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Template.php(375): craft\web\twig\Template->display(Array)
#12 C:\Users\xmr\Desktop\foobar\vendor\twig\twig\lib\Twig\Environment.php(289): Twig_Template->render(Array)
#13 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\View.php(331): Twig_Environment->render('pages', Array)
#14 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\View.php(378): craft\web\View->renderTemplate('pages', Array)
#15 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\Controller.php(155): craft\web\View->renderPageTemplate('pages', Array)
#16 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\controllers\TemplatesController.php(78): craft\web\Controller->renderTemplate('pages', Array)
#17 [internal function]: craft\controllers\TemplatesController->actionRender('pages', Array)
#18 C:\Users\xmr\Desktop\foobar\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#19 C:\Users\xmr\Desktop\foobar\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\Controller.php(103): yii\base\Controller->runAction('render', Array)
#21 C:\Users\xmr\Desktop\foobar\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('render', Array)
#22 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#23 C:\Users\xmr\Desktop\foobar\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#24 C:\Users\xmr\Desktop\foobar\vendor\craftcms\cms\src\web\Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 C:\Users\xmr\Desktop\foobar\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 C:\Users\xmr\Desktop\foobar\web\index.php(21): yii\base\Application->run()
#27 {main}
```

This is my custom SEOmatic template directives:

```twig
{% do seomatic.link.get("alternate").hreflang("#{craft.app.language}") %}
{% do seomatic.script.get("googleTagManager").include(true) %}
{% do seomatic.tag.get("referrer").include(false) %}
```

And the search part:

```twig
<form action="{{ url('search') }}" role="search">
  <div class="form">
    <input type="search" name="q" placeholder="Search">
    <button type="submit" class="btn">Search</button>
  </div>
</form>
```

Maybe this is done wrong?

Thanks!

**Comment by XhmikosR** [comment]
OK, I think I see why. The page is excluded from sitemap. If I include it in the sitemap then the error isn't thrown.

**Comment by khalwat** [comment]
Yes, you should be checking for null:

```
{% set alternate = seomatic.link.get("alternate") %}
{% if alternate %}
    {% do alternate.hreflang("#{craft.app.language} %}
{% endif %}
```
...if you're doing something to ensure that these tags may or may not be present.

**Comment by XhmikosR** [comment]
Thanks, I figured so after I made the issue. It's just that I didn't expect this to be thrown in the first place, but I guess it's not an error on your side.
