### ISSUE TITLE
Seomatic breaks console queue with redis cache

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#217]
1. Run your queue as console (e.g. `craft queue/listen`, with `'runQueueAutomatically' => false`)
2. Use a Redis cache, eg
    ```
        'cache' => [
            'class' => \yii\redis\Cache::class,
            'defaultDuration' => 60*60*24,
        ],
    ```
3. Run a task (e.g. resave a section)
4. 😢 

Do the same with Seomatic disabled, queue task works fine

Resulting error:
```
2018-09-07 16:32:33 [-][-][-][error][yii\redis\Connection] Failed to open redis DB connection (redis:6379, database=0): 0 - php_network_getaddresses: getaddrinfo failed: Name or service not known
2018-09-07 16:32:33 [-][-][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2018-09-07 16:32:33 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [1] Resaving Legal entries (attempt: 1) - Error (time: 1.429s): Failed to open redis DB connection (redis:6379, database=0): 0 - php_network_getaddresses: getaddrinfo failed: Name or service not known
2018-09-07 16:32:33 [-][-][-][error][yii\db\Exception] yii\db\Exception: Failed to open redis DB connection (redis:6379, database=0): 0 - php_network_getaddresses: getaddrinfo failed: Name or service not known in /app/vendor/composer/yiisoft/yii2-redis/src/Connection.php:565
Stack trace:
#0 /app/vendor/composer/yiisoft/yii2-redis/src/Connection.php(665): yii\redis\Connection->open()
#1 /app/vendor/composer/yiisoft/yii2-redis/src/Cache.php(199): yii\redis\Connection->executeCommand('MSET', Array)
#2 /app/vendor/composer/yiisoft/yii2/caching/Cache.php(287): yii\redis\Cache->setValues(Array, 0)
#3 /app/vendor/composer/yiisoft/yii2/caching/TagDependency.php(96): yii\caching\Cache->multiSet(Array)
#4 /app/vendor/composer/yiisoft/yii2/caching/TagDependency.php(80): yii\caching\TagDependency::touchKeys(Object(yii\redis\Cache), Array)
#5 /app/vendor/composer/nystudio107/craft-seomatic/src/services/MetaContainers.php(654): yii\caching\TagDependency::invalidate(Object(yii\redis\Cache), 'seomatic_metaco...')
#6 /app/vendor/composer/nystudio107/craft-seomatic/src/services/MetaBundles.php(409): nystudio107\seomatic\services\MetaContainers->invalidateContainerCacheByPath('', 4)
#7 /app/vendor/composer/nystudio107/craft-seomatic/src/Seomatic.php(560): nystudio107\seomatic\services\MetaBundles->invalidateMetaBundleByElement(Object(craft\elements\Entry), false)
#8 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(craft\events\ElementEvent))
#9 /app/vendor/composer/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#10 /app/vendor/composer/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#11 /app/vendor/composer/craftcms/cms/src/services/Elements.php(542): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#12 /app/vendor/composer/craftcms/cms/src/services/Elements.php(1395): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, false)
#13 /app/vendor/composer/craftcms/cms/src/services/Elements.php(500): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), false, Array)
#14 /app/vendor/composer/craftcms/cms/src/queue/jobs/ResaveElements.php(73): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#15 /app/vendor/composer/yiisoft/yii2-queue/src/Queue.php(214): craft\queue\jobs\ResaveElements->execute(Object(craft\queue\Queue))
#16 /app/vendor/composer/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('1', 'O:31:"craft\\que...', '3600', '1')
#17 /app/vendor/composer/yiisoft/yii2-queue/src/cli/Command.php(145): yii\queue\cli\Queue->execute('1', 'O:31:"craft\\que...', '3600', '1', '')
#18 [internal function]: yii\queue\cli\Command->actionExec('1', '3600', '1', '')
#19 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/composer/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('exec', Array)
#22 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('exec', Array)
#23 /app/vendor/composer/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#24 /app/vendor/composer/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/exec', Array)
#25 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /app/bin/craft(26): yii\base\Application->run()
#27 {main}
Additional Information:
php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by khalwat** [comment]
So looking at the stack trace, and knowing how SEOmatic does its caching... I'd be super surprised if this was something specific to SEOmatic.

Very few things in Craft use the Yii2 cache; so it is probably more likely that SEOmatic (which does leverage the Yii2 cache) is exposing the issue, not that it's causing it.

FWIW, I have SEOmatic running on several sites that use Redis as a caching method, without incident. So it could be a config issue with Redis, or it could be a new bug in Yii2.
