### ISSUE TITLE
Seomatic breaks console

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#222]
```2018-09-14 08:33:57 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [4059] Updating element slugs and URIs (attempt: 1) - Error (time: 0.069s): Getting unknown property: yii\console\Response::statusCode
2018-09-14 08:33:57 [-][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: yii\console\Response::statusCode in /app/vendor/composer/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /app/vendor/composer/nystudio107/craft-seomatic/src/services/MetaContainers.php(169): yii\base\Component->__get('statusCode')
#1 /app/vendor/composer/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('/', '11')
#2 /app/vendor/composer/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#3 /app/vendor/composer/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#4 /app/vendor/composer/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#5 /app/vendor/composer/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#6 /app/vendor/composer/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#7 /app/vendor/composer/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#8 /app/vendor/composer/craftcms/cms/src/web/View.php(519): Twig_Template->render(Array)
#9 /app/vendor/composer/craftcms/cms/src/helpers/ElementHelper.php(149): craft\web\View->renderObjectTemplate('{{ (_variables....', Object(craft\elements\Entry), Array)
#10 /app/vendor/composer/craftcms/cms/src/helpers/ElementHelper.php(92): craft\helpers\ElementHelper::_renderUriFormat('{parent.uri}/{s...', Object(craft\elements\Entry))
#11 /app/vendor/composer/craftcms/cms/src/services/Elements.php(639): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#12 /app/vendor/composer/craftcms/cms/src/queue/jobs/UpdateElementSlugsAndUris.php(128): craft\services\Elements->updateElementSlugAndUri(Object(craft\elements\Entry), true, false, false)
#13 /app/vendor/composer/craftcms/cms/src/queue/jobs/UpdateElementSlugsAndUris.php(79): craft\queue\jobs\UpdateElementSlugsAndUris->_processElements(Object(craft\queue\Queue), Object(craft\elements\db\EntryQuery))```

**Comment by timkelty** [comment]
Need an `getIsConsoleRequest` in there…`statusCode` is only available in web.

**Comment by Wiejeben** [comment]
Getting the same exception when trying to compile a template for sending an email via Queues.

**Comment by khalwat** [comment]
Fixed in: https://github.com/nystudio107/craft-seomatic/commit/9e3f754857637c3f06083eb37da85455ce8c13c7

You can pull from `dev-develop` or wait until I cut a release later today!
