### ISSUE TITLE
SEO Matic enabled 502s site

### ISSUE THREAD

**Issue by proposifymax** [nystudio107/craft-seomatic#280]
We utilize static html caching for performance and stability reasons but got alerted that dynamic URLs (i.e. not cached ones but with URL parameters like gclid, etc were unable to access the site).

Tailing the craft logs this was repeated over and over:

```
2018-12-02 21:18:46 [-][-][c119vll54tf4kj8scd29f9ldbd][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaScript::bodyTemplateString in /var/app/current/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /var/app/current/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('bodyTemplateStr...', NULL)
#1 /var/app/current/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(nystudio107\seomatic\models\MetaScript), Array)
#2 /var/app/current/vendor/nystudio107/craft-seomatic/src/models/MetaScript.php(90): yii\base\BaseObject->__construct(Array)
#3 /var/app/current/vendor/nystudio107/craft-seomatic/src/models/MetaScriptContainer.php(114): nystudio107\seomatic\models\MetaScript::create(Array)
#4 /var/app/current/vendor/nystudio107/craft-seomatic/src/base/Container.php(46): nystudio107\seomatic\models\MetaScriptContainer->normalizeContainerData()
#5 /var/app/current/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(221): nystudio107\seomatic\base\Container::create(Array)
#6 /var/app/current/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(136): nystudio107\seomatic\models\MetaBundle->normalizeMetaBundleData(true)
#7 /var/app/current/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(120): nystudio107\seomatic\models\MetaBundle::create(Array, true)
#8 /var/app/current/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(695): nystudio107\seomatic\services\MetaBundles->getGlobalMetaBundle(1)
#9 /var/app/current/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(198): nystudio107\seomatic\services\MetaContainers->loadGlobalMetaContainers(1)
#10 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#11 /var/app/current/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#12 /var/app/current/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(206): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#13 /var/app/current/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('', '1')
#14 /var/app/current/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#15 /var/app/current/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#16 /var/app/current/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#17 /var/app/current/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#18 /var/app/current/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#19 /var/app/current/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#20 /var/app/current/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#21 /var/app/current/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('index', Array)
#22 /var/app/current/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('index', Array)
#23 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('index', Array)
#24 /var/app/current/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('index', Array)
#25 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#26 /var/app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /var/app/current/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#29 /var/app/current/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#30 /var/app/current/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#31 /var/app/current/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 /var/app/current/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 /var/app/current/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /var/app/current/web/index.php(23): yii\base\Application->run()
#35 {main}
2018-12-02 21:18:45 [-][-][c119vll54tf4kj8scd29f9ldbd][info][application] $_GET = []

$_POST = []

$_FILES = []

$_COOKIE = []

$_SESSION = [
    '****' => []
]

$_SERVER = [
    'MOUNT_DIRECTORY' => '/efs'
    'ENVIRONMENT' => 'production'
    'REGION' => 'us-east-1'
    'PHP_MEMORY_LIMIT' => '256M'
    'PHP_MAX_EXECUTION_TIME' => '60'
    'PHP_DISPLAY_ERRORS' => 'Off'
    'PHP_COMPOSER_OPTIONS' => ''
    'PHP_ALLOW_URL_FOPEN' => 'On'
    'PHP_ZLIB_OUTPUT_COMPRESSION' => 'On'
    'PHP_DOCUMENT_ROOT' => '/web'
    'PHP_DATE_TIMEZONE' => 'UTC'
    'HTTP_HOST' => '*.*.*.*'
    'HTTP_CONNECTION' => 'close'
    'HTTP_USER_AGENT' => 'ELB-HealthChecker/2.0'
    'HTTP_ACCEPT_ENCODING' => 'gzip, compressed'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache'
    'SERVER_NAME' => '*.*.*.*'
    'SERVER_ADDR' => '*.*.*.*'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '*.*.*.*'
    'DOCUMENT_ROOT' => '/var/www/html/web'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/web'
    'SERVER_ADMIN' => 'root@localhost'
    'SCRIPT_FILENAME' => '/var/www/html/web/index.php'
    'REMOTE_PORT' => '34486'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1543799925.898
    'REQUEST_TIME' => 1543799925
    'DB_DRIVER' => 'mysql'
]
```

Even the /admin panel wasn't loading. I had to directly connect to the database and change the seomatic enabled flag in the plugins table to 0 in order for the admin panel to even work.

**Comment by khalwat** [comment]
So this to me looks like the database was updated somewhere, but `composer update` was not done on the production server, or did not succeed properly.

Basically, the version of SEOmatic that you have installed is not the latest version, but something updated the storage in the database to a data structure in accordance with the latest version.

`composer update` 

...and you should be good to go @proposifymax

**Comment by proposifymax** [comment]
Updating SEO matic via composer did solve it but that wasn't done when the error occurred (over the weekend where no-one would be updating composer packages, let alone deploying them).

**Comment by khalwat** [comment]
So I don't see how that could happen. That's a new property on that model, but only the update would cause it to save that new property in the database... 

The only way I can see this happening is if the update was done in one environment, the database was then updated, and the database from that environment is pulled into another environment where the update has _not_ been installed yet.
