### ISSUE TITLE
Setting unknown property: additionalSitemaps

### ISSUE THREAD

**Issue by MattWilcox** [nystudio107/craft-seomatic#287]
I'm currently getting the following error any time I try and visit any page of my site:
`unknown property: nystudio107\seomatic\models\MetaSiteVars::additionalSitemaps`

This is happening even on the CMS login screen, which means I can't log in to do anything about it.

This is a fresh project, based on a "default build" that is working - it's a copy of the files, copy of the database, and tweak of the configs to reflect that.

I've tried `rm -rf vendor/ && rm composer.lock && composer update` to no avail, I've changed permissions on a bunch of folders, but no dice.

yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::additionalSitemaps in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('additionalSitem...', Array)
#1 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(nystudio107\seomatic\models\MetaSiteVars), Array)
#2 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaSiteVars.php(42): yii\base\BaseObject->__construct(Array)
#3 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(166): nystudio107\seomatic\models\MetaSiteVars::create(Array)
#4 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(136): nystudio107\seomatic\models\MetaBundle->normalizeMetaBundleData(true)
#5 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(120): nystudio107\seomatic\models\MetaBundle::create(Array, true)
#6 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(696): nystudio107\seomatic\services\MetaBundles->getGlobalMetaBundle(1)
#7 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(198): nystudio107\seomatic\services\MetaContainers->loadGlobalMetaContainers(1)
#8 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#9 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#10 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(206): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 1, Object(yii\caching\TagDependency))
#11 /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('login', '1')
#12 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#13 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#14 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#15 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#16 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#18 /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#19 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('login', Array)
#20 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('login', Array)
#21 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('login', Array)
#22 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('login', Array)
#23 [internal function]: craft\controllers\TemplatesController->actionRender('login', Array)
#24 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#26 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#27 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#28 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#29 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#30 /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#31 /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /Users/matt/Sites/abergele/7_website/public/index.php(21): yii\base\Application->run()
#33 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::additionalSitemaps
1. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Component.php at line 209
200201202203204205206207208209210211212213214215216217218                                    $behavior->$name = $value;
                return;
            }
        }
 
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        }
 
        throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     *
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set
                
2. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/BaseYii.php at line 546 – yii\base\Component::__set('additionalSitemaps', [])
3. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/BaseObject.php at line 107 – yii\BaseYii::configure(nystudio107\seomatic\models\MetaSiteVars, ['siteName' => 'Vanilla Build MERCURY', 'identity' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'none', 'computedType' => 'LocalBusiness', ...], 'creator' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'ProfessionalService', 'computedType' => 'ProfessionalService', ...], 'twitterHandle' => '', ...])
4. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaSiteVars.php at line 42 – yii\base\BaseObject::__construct(['siteName' => 'Vanilla Build MERCURY', 'identity' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'none', 'computedType' => 'LocalBusiness', ...], 'creator' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'ProfessionalService', 'computedType' => 'ProfessionalService', ...], 'twitterHandle' => '', ...])
36373839404142434445464748                         * @param array $config
     *
     * @return null|MetaSiteVars
     */
    public static function create(array $config = [])
    {
        $model = new MetaSiteVars($config);
        $model->normalizeData();
 
        return $model;
    }
 
    // Public Properties
                
5. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php at line 166 – nystudio107\seomatic\models\MetaSiteVars::create(['siteName' => 'Vanilla Build MERCURY', 'identity' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'none', 'computedType' => 'LocalBusiness', ...], 'creator' => ['siteType' => 'Organization', 'siteSubType' => 'LocalBusiness', 'siteSpecificType' => 'ProfessionalService', 'computedType' => 'ProfessionalService', ...], 'twitterHandle' => '', ...])
160161162163164165166167168169170171172                            // Meta global variables
        if ($this->metaGlobalVars !== null && \is_array($this->metaGlobalVars)) {
            $this->metaGlobalVars = MetaGlobalVars::create($this->metaGlobalVars);
        }
        // Meta site variables
        if ($this->metaSiteVars !== null && \is_array($this->metaSiteVars)) {
            $this->metaSiteVars = MetaSiteVars::create($this->metaSiteVars);
        }
        // Meta sitemap variables
        if ($this->metaSitemapVars !== null && \is_array($this->metaSitemapVars)) {
            $this->metaSitemapVars = MetaSitemapVars::create($this->metaSitemapVars);
        }
        // Meta bundle settings
                
6. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php at line 136 – nystudio107\seomatic\models\MetaBundle::normalizeMetaBundleData(true)
130131132133134135136137138139140141142                         */
    public static function create(array $config = [], bool $parse = true)
    {
        self::cleanProperties(__CLASS__, $config);
        $model = new MetaBundle($config);
        if ($model) {
            $model->normalizeMetaBundleData($parse);
        }
 
        return $model;
    }
 
    /**
                
7. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php at line 120 – nystudio107\seomatic\models\MetaBundle::create(['bundleVersion' => '1.0.46', 'sourceBundleType' => '__GLOBAL_BUNDLE__', 'sourceId' => '1', 'sourceName' => '__GLOBAL_BUNDLE__', ...], true)
114115116117118119120121122123124125126                                    'sourceSiteId' => $sourceSiteId,
            ])
            ->one();
        if (!empty($metaBundleArray)) {
            // Get the attributes from the db
            $metaBundleArray = array_diff_key($metaBundleArray, array_flip(self::IGNORE_DB_ATTRIBUTES));
            $metaBundle = MetaBundle::create($metaBundleArray, $parse);
            if ($parse) {
                $this->syncBundleWithConfig($metaBundle);
            }
        } else {
            // If it doesn't exist, create it
            $metaBundle = $this->createGlobalMetaBundleForSite($sourceSiteId);
                
8. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php at line 696 – nystudio107\seomatic\services\MetaBundles::getGlobalMetaBundle(1)
690691692693694695696697698699700701702                        protected function loadGlobalMetaContainers(int $siteId = null)
    {
        Craft::beginProfile('MetaContainers::loadGlobalMetaContainers', __METHOD__);
        if ($siteId === null) {
            $siteId = Craft::$app->getSites()->currentSite->id ?? 1;
        }
        $metaBundle = Seomatic::$plugin->metaBundles->getGlobalMetaBundle($siteId);
        if ($metaBundle) {
            // Meta global vars
            $this->metaGlobalVars = $metaBundle->metaGlobalVars;
            // Meta site vars
            $this->metaSiteVars = $metaBundle->metaSiteVars;
            // Meta sitemap vars
                
9. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php at line 198 – nystudio107\seomatic\services\MetaContainers::loadGlobalMetaContainers(1)
192193194195196197198199200201202203204                                        $this::CACHE_KEY.$cacheKey,
                    function () use ($uri, $siteId) {
                        Craft::info(
                            'Meta container cache miss: '.$uri.'/'.$siteId,
                            __METHOD__
                        );
                        $this->loadGlobalMetaContainers($siteId);
                        $this->loadContentMetaContainers();
                        $this->loadFieldMetaContainers();
                        DynamicMetaHelper::addDynamicMetaToContainers($uri, $siteId);
 
                        return [$this->metaGlobalVars, $this->metaSiteVars, $this->metaSitemapVars, $this->metaContainers];
                    },
                
10. nystudio107\seomatic\services\MetaContainers::nystudio107\seomatic\services\{closure}(yii\caching\FileCache)
11. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/caching/Cache.php at line 575 – call_user_func(Closure, yii\caching\FileCache)
12. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php at line 206 – yii\caching\Cache::getOrSet('seomatic_metacontainer_login1pag...', Closure, 1, yii\caching\TagDependency)
200201202203204205206207208209210211212                                            $this->loadFieldMetaContainers();
                        DynamicMetaHelper::addDynamicMetaToContainers($uri, $siteId);
 
                        return [$this->metaGlobalVars, $this->metaSiteVars, $this->metaSitemapVars, $this->metaContainers];
                    },
                    Seomatic::$cacheDuration,
                    $dependency
                );
            }
            Seomatic::$seomaticVariable->init();
            MetaValueHelper::cache();
            Seomatic::$loadingContainers = false;
        }
                
13. in /Users/matt/Sites/abergele/7_website/craft/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php at line 47 – nystudio107\seomatic\services\MetaContainers::loadMetaContainers('login', '1')
41424344454647484950515253                                        $requestPath = $request->getPathInfo();
                } catch (InvalidConfigException $e) {
                    Craft::error($e->getMessage(), __METHOD__);
                }
            }
            // Load the meta containers for this page
            Seomatic::$plugin->metaContainers->loadMetaContainers($requestPath, null);
        }
 
        return ['seomatic' => Seomatic::$seomaticVariable];
    }
 
    /**
                
14. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/ExtensionSet.php at line 339 – nystudio107\seomatic\twigextensions\SeomaticTwigExtension::getGlobals()
15. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php at line 903 – Twig_ExtensionSet::getGlobals()
16. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php at line 923 – Twig_Environment::getGlobals()
17. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Template.php at line 367 – Twig_Environment::mergeGlobals([])
18. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/twig/Template.php at line 31 – Twig_Template::display([], [])
19. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Template.php at line 375 – craft\web\twig\Template::display([])
20. in /Users/matt/Sites/abergele/7_website/craft/vendor/twig/twig/lib/Twig/Environment.php at line 289 – Twig_Template::render([])
21. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/View.php at line 331 – Twig_Environment::render('login', [])
325326327328329330331332333334335336337                            // Render and return
        $renderingTemplate = $this->_renderingTemplate;
        $this->_renderingTemplate = $template;
        Craft::beginProfile($template, __METHOD__);
 
        try {
            $output = $this->getTwig()->render($template, $variables);
        } catch (\RuntimeException $e) {
            if (!YII_DEBUG) {
                // Throw a generic exception instead
                throw new Exception('An error occurred when rendering a template.', 0, $e);
            }
            throw $e;
                
22. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/View.php at line 378 – craft\web\View::renderTemplate('login', [])
372373374375376377378379380381382383384                            ob_implicit_flush(false);
 
        $isRenderingPageTemplate = $this->_isRenderingPageTemplate;
        $this->_isRenderingPageTemplate = true;
 
        $this->beginPage();
        echo $this->renderTemplate($template, $variables);
        $this->endPage();
 
        $this->_isRenderingPageTemplate = $isRenderingPageTemplate;
 
        $output = ob_get_clean();
 
                
23. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Controller.php at line 156 – craft\web\View::renderPageTemplate('login', [])
150151152153154155156157158159160161162                                }
 
            $headers->set('content-type', $mimeType . '; charset=' . $response->charset);
        }
 
        // Render and return the template
        $response->data = $this->getView()->renderPageTemplate($template, $variables);
 
        // Prevent a response formatter from overriding the content-type header
        $response->format = YiiResponse::FORMAT_RAW;
 
        return $response;
    }
                
24. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php at line 78 – craft\web\Controller::renderTemplate('login', [])
72737475767778798081828384                     
        // Merge any additional route params
        $routeParams = Craft::$app->getUrlManager()->getRouteParams();
        unset($routeParams['template'], $routeParams['template']);
        $variables = array_merge($variables, $routeParams);
 
        return $this->renderTemplate($template, $variables);
    }
 
    /**
     * Shows the 'offline' template.
     *
     * @return Response
                
25. craft\controllers\TemplatesController::actionRender('login', [])
26. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([craft\controllers\TemplatesController, 'actionRender'], ['login', []])
27. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Controller.php at line 157 – yii\base\InlineAction::runWithParams(['template' => 'login', 'p' => 'secretadmin/login/'])
28. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Controller.php at line 104 – yii\base\Controller::runAction('render', ['template' => 'login', 'p' => 'secretadmin/login/'])
9899100101102103104105106107108109110                        /**
     * @inheritdoc
     */
    public function runAction($id, $params = [])
    {
        try {
            return parent::runAction($id, $params);
        } catch (\Throwable $e) {
            if (Craft::$app->getRequest()->getAcceptsJson()) {
                Craft::$app->getErrorHandler()->logException($e);
                $message = $e->getMessage();
                if ($e instanceof ClientException) {
                    $statusCode = $e->getCode();
                
29. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Module.php at line 528 – craft\web\Controller::runAction('render', ['template' => 'login', 'p' => 'secretadmin/login/'])
30. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Application.php at line 282 – yii\base\Module::runAction('templates/render', ['template' => 'login', 'p' => 'secretadmin/login/'])
276277278279280281282283284285286287288                         * @param string $route
     * @param array $params
     * @return Response|null The result of the action, normalized into a Response object
     */
    public function runAction($route, $params = [])
    {
        $result = parent::runAction($route, $params);
 
        if ($result !== null) {
            if ($result instanceof Response) {
                return $result;
            }
 
                
31. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/web/Application.php at line 103 – craft\web\Application::runAction('templates/render', ['template' => 'login', 'p' => 'secretadmin/login/'])
32. in /Users/matt/Sites/abergele/7_website/craft/vendor/craftcms/cms/src/web/Application.php at line 271 – yii\web\Application::handleRequest(craft\web\Request)
265266267268269270271272273274275276277                            // If this is an action request, call the controller
        if (($response = $this->_processActionRequest($request)) !== null) {
            return $response;
        }
 
        // If we're still here, finally let Yii do it's thing.
        return parent::handleRequest($request);
    }
 
    /**
     * @inheritdoc
     * @param string $route
     * @param array $params
                
33. in /Users/matt/Sites/abergele/7_website/craft/vendor/yiisoft/yii2/base/Application.php at line 386 – craft\web\Application::handleRequest(craft\web\Request)
34. in /Users/matt/Sites/abergele/7_website/public/index.php at line 21 – yii\base\Application::run()
15161718192021                        (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}
 
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
                
$_GET = [
    'p' => 'secretadmin/login/',
];

$_COOKIE = [
    'CraftSessionId' => 'mm7fn0si7op9b0d2trncp23ttu',
];

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [],
    '1031b8c41dfff97a311a7ac99863bdc5__returnUrl' => '/secretadmin/',
];
Yii Framework
2019-01-02, 11:07:04
Apache/2.4.33 (Unix) PHP/7.1.16
Yii Framework/2.0.15.1

**Comment by MattWilcox** [comment]
My idiocy - there was a file/db version mis-match because I didn't push some changes to GIT before I cloned the source project. Sorry Andrew!
