### ISSUE TITLE
Adding extra data to JSON-LD

### ISSUE THREAD

**Issue by MGxpwr** [nystudio107/craft-seomatic#310]
I'm trying to add some extra data like a location and start date to de main entity of our site. Its set to type Event and Google expects the two fields mentioned.

Now when I try the following piece of code:
```twig
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% set eventJsonLd = seomatic.jsonLd.create({

  'type': 'Place',
  'address': {
    '@type': 'PostalAddress',
    'addressLocality': 'Some place',
    'addressRegion': 'Some Region',
    'postalCode': '12345',
    'streetAddress': 'Some street'
  },
  'name': 'Some name',

}, false) %}

{% do mainEntity.location(eventJsonLd) %}
```

Gives me this error
```
yii\base\InvalidArgumentException: Property location doesn't exist in /home/vagrant/Code/drakenbootfestival/vendor/nystudio107/craft-seomatic/src/base/FluentModel.php:69
Stack trace:
#0 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Extension/Core.php(1626): nystudio107\seomatic\base\FluentModel->__call('location', Array)
#1 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(nystudio107\seomatic\models\jsonld\WebPage), 'location', Array, 'method', false, false)
#2 /home/vagrant/Code/drakenbootfestival/storage/runtime/compiled_templates/2e/2ebdd15acdfde5ed43d99f20e7965b0f1b89deaccbf815a73cb38cf0c034f8e7.php(342): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(nystudio107\seomatic\models\jsonld\WebPage), 'location', Array, 'method')
#3 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_1daeb523bb9288968300574e488696ca1e3f532385e42b4ba8fe26e265d515b6->doDisplay(Array, Array)
#4 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#5 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#6 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#7 /home/vagrant/Code/drakenbootfestival/storage/runtime/compiled_templates/7b/7b152ef20d52d453026524c725afe3b538d380f995888efc8ba411376050b93c.php(36): craft\web\twig\Template->display(Array, Array)
#8 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_ee169488503811981ee25618dd7f81406c804569682870fbd68186fee6c221e0->doDisplay(Array, Array)
#9 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#10 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#12 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#13 /home/vagrant/Code/drakenbootfestival/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#14 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('index', Array)
#15 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('index', Array)
#16 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('index', Array)
#17 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('index', Array)
#18 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#19 /home/vagrant/Code/drakenbootfestival/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /home/vagrant/Code/drakenbootfestival/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#22 /home/vagrant/Code/drakenbootfestival/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#23 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#24 /home/vagrant/Code/drakenbootfestival/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#25 /home/vagrant/Code/drakenbootfestival/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /home/vagrant/Code/drakenbootfestival/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /home/vagrant/Code/drakenbootfestival/public/index.php(42): yii\base\Application->run()
#28 {main}
```

When I try to do this to the Identity json+ld I do not get this error and it works fine.
Any idea on what I might be doing wrong? And what I might do to fix this?

**Comment by khalwat** [comment]
So that model definitely does have a location property:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/jsonld/Event.php#L222

...which makes me wonder if the `mainEntityOfPage` is indeed an `Event`? Can you verify by doing something like:

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{{ dump(mainEntity) }}
```

...and see what it outputs for the JSON-LD type?

**Comment by MGxpwr** [comment]
It was outputting `object(nystudio107\seomatic\models\jsonld\WebPage)` So of the type WebPage. 

The thing was, I was expecting when I left the main entity empty on a per entry basis it would fall back to the General setting of the global SEO, but it falls back to content SEO which is set on a section basis. And there it was set to WebPage and you can't leave that empty.

Is it possible it will fall back to the global settings if left empty on per section basis? In my case, it would because the whole site is for an event.

**Comment by khalwat** [comment]
It can fall back if the settings in the Content SEO for a section are set to nothing; just change them to the blank entry at the top, and it'll fall back on the global setting.

**Comment by MGxpwr** [comment]
![screenshot 2019-02-11 at 10 41 19](https://user-images.githubusercontent.com/3479490/52555301-96137c00-2de9-11e9-9166-271038184e41.png)

Well, that's the thing, there is no blank entry at the top.

**Comment by khalwat** [comment]
mmmm yes this should probably be fixed.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/e06607827a5e0686e7d722887a9e01d16b6592c1

![google chromescreensnapz1471](https://user-images.githubusercontent.com/7570798/52876169-6b486100-3124-11e9-9263-629c287aa23c.png)

**Comment by MGxpwr** [comment]
Thanks for the fix 😄
