### ISSUE TITLE
Exceptions during content migrations

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#37]
After installing this plugin we hit an exception running a content migration when attempting to save a new section. Here's the relevant bit:

```php
Exception: Calling unknown method: craft\console\Request::getPathInfo() (/var/www/html/vendor/yiisoft/yii2/base/Component.php:300)
#0 /var/www/html/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(38): yii\base\Component->__call('getPathInfo', Array)
```

Looks like it's assuming the `request` component is a `craft\web\Request` instance.

**Comment by khalwat** [comment]
Yeah I think we can safely not load our Twig extension if it's a console request. :)

**Comment by khalwat** [comment]
Come to think of it, this actually sounds sort of like a bug elsewhere as well. I'll fix it in SEOmatic, but some plugin seems like it's instantiating/using Twig on console requests, which is very odd.

**Comment by khalwat** [comment]
The reason I say that is I'm able to run console commands just fine with SEOmatic installed, e.g.:

```
vagrant@homestead ~/sites/craft3 $ ./craft image-optimize/optimize/create
Creating optimized image variants
Optimizing images in Blog
```
So I'm assuming some plugin somewhere is instantiating and using Twig during a console request... which might be okay I guess, but I think it's more likely a bug of some kind.

**Comment by mgburns** [comment]
In our case it's because we were saving a new section that used Twig in the section title. Here's a more complete stack trace for you:

```shell
> saving "Contact" section ...Exception: Calling unknown method: craft\console\Request::getPathInfo() (/var/www/html/vendor/yiisoft/yii2/base/Component.php:300)
#0 /var/www/html/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(38): yii\base\Component->__call('getPathInfo', Array)
#1 /var/www/html/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#2 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#3 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#4 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#6 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/View.php(475): Twig_Template->render(Array)
#8 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(924): craft\web\View->renderObjectTemplate('{{object.sectio...', Object(craft\elements\Entry))
#9 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(347): craft\elements\Entry->beforeSave(true)
#10 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1144): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(541): craft\services\Sections->_onSaveSingle(Object(craft\models\Section), true, Array)
#12 /var/www/html/src/migrations/Base.php(434): craft\services\Sections->saveSection(Object(craft\models\Section))
```

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4e5d6e6664d70b666f5d570178dd89ca1b36f06f
