### ISSUE TITLE
Error when updating entries from console command

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft-seomatic#39]
Getting the following error when trying to update an entry from a console command:

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getSegments()'

in /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /Users/rias/Code/primeretail/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(154): yii\base\Component->__call('getSegments', Array)
#1 /Users/rias/Code/primeretail/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(94): nystudio107\seomatic\helpers\DynamicMeta::addMetaJsonLdBreadCrumbs(1)
#2 /Users/rias/Code/primeretail/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(150): nystudio107\seomatic\helpers\DynamicMeta::addDynamicMetaToContainers('/', 1)
#3 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#4 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#5 /Users/rias/Code/primeretail/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(155): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), NULL, Object(yii\caching\TagDependency))
#6 /Users/rias/Code/primeretail/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(43): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('/', '1')
#7 /Users/rias/Code/primeretail/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#8 /Users/rias/Code/primeretail/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#9 /Users/rias/Code/primeretail/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#10 /Users/rias/Code/primeretail/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#11 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#12 /Users/rias/Code/primeretail/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#13 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/web/View.php(475): Twig_Template->render(Array)
#14 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/helpers/ElementHelper.php(190): craft\web\View->renderObjectTemplate('ons-aanbod/{{ob...', Object(stdClass))
#15 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/helpers/ElementHelper.php(66): craft\helpers\ElementHelper::doesUriFormatHaveSlugTag('ons-aanbod/{slu...')
#16 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/validators/ElementUriValidator.php(49): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#17 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/validators/Validator.php(267): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#18 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#19 /Users/rias/Code/primeretail/vendor/craftcms/cms/src/services/Elements.php(373): yii\base\Model->validate()
#20 /Users/rias/Code/primeretail/modules/sitemodule/src/console/controllers/OmnicasaController.php(89): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#21 [internal function]: modules\sitemodule\console\controllers\OmnicasaController->actionSync()
#22 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('sync', Array)
#25 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('sync', Array)
#26 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('site-module/omn...', Array)
#27 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('site-module/omn...', Array)
#28 /Users/rias/Code/primeretail/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /Users/rias/Code/primeretail/craft(43): yii\base\Application->run()
#30 {main}

```

**Comment by khalwat** [comment]
gah! Thanks, will address.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/5253e6b3e0e3f3cff6a42d6a17f51e1ae540d3c4
