### ISSUE TITLE
Template and array error

### ISSUE THREAD

**Issue by espensgr** [nystudio107/craft-seomatic#41]
I get `Variable "seomatic" does not exist localy.` on the Global SEO, Content SEO and Content SEO pages in admin.
On my live i get a merge filter array on the same pages.
![skjermbilde 2018-03-27 09 43 48](https://user-images.githubusercontent.com/3862891/37953560-8698a84c-31a3-11e8-8336-61c6c4a94be8.png)

I also get a error on rendering `_sidebars/entry-preview.twig` in my entries. 
![skjermbilde 2018-03-27 09 41 05](https://user-images.githubusercontent.com/3862891/37953447-35e3f15e-31a3-11e8-9f1a-e02d9cdea063.png)

Have tried to uninstall and install again, but nothing changes. i have RC16.1 and SEOmatic 3.0.0-beta.18

**Comment by khalwat** [comment]
Something seems very wrong with the install; do you have any other plugins installed @espensgr ? Can you list them?

Any chance you can enable `devMode` and get me a full stack trace?

**Comment by espensgr** [comment]
Sure thing.
Here is the plugins (CKEditor is not installed)
![skjermbilde 2018-03-27 14 04 37](https://user-images.githubusercontent.com/3862891/37966148-d6045772-31c7-11e8-8f68-c452680a5924.png)

Her is the stacktrace
```
Twig_Error_Runtime: Variable "seomatic" does not exist. in /Users/bruker1/Lokale sider/mustasj/vendor/nystudio107/craft-seomatic/src/templates/_includes/googlePreview.twig:1
Stack trace:
#0 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/0b/0bc93c6957ae75827d55ddd85aeeaacad6182d09143a7c4ddb3871da81af311f.php(23): __TwigTemplate_c470bb6d3c475b6d3d394ced1debbb48fba4faa4c811af512a077ebde116f822->{closure}()
#1 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_c470bb6d3c475b6d3d394ced1debbb48fba4faa4c811af512a077ebde116f822->doDisplay(Array, Array)
#2 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#5 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/c8/c86e5ae8504163af19f5ffc7843006938a2ae0711ed344d45849204237d8f05a.php(34): craft\web\twig\Template->display(Array)
#6 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_dd3522311025dcc3be2bd7d456ce57d24aa435f0f62e3a222237cda63929666e->doDisplay(Array, Array)
#7 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#8 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#9 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#10 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/20/20f19189a39ec0a39f38524c942363b193ff82ed88585141ea7a1396f5538c96.php(94): craft\web\twig\Template->display(Array)
#11 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_72414fe613bfd69cbef959d85751d8793f29e2bb6eee26a221200e9a5be3fbe1->block_content(Array, Array)
#12 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/b5/b586f7910f5dd6690e36453b733d83cb359c13791dc83504a02a1402a257a42d.php(644): Twig_Template->displayBlock('content', Array, Array)
#13 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_18c937ced3dc4a1acf73d70763ac8bf059e22c63ea3c75c929587e8104c4ff2a->block_main(Array, Array)
#14 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/b5/b586f7910f5dd6690e36453b733d83cb359c13791dc83504a02a1402a257a42d.php(541): Twig_Template->displayBlock('main', Array, Array)
#15 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_18c937ced3dc4a1acf73d70763ac8bf059e22c63ea3c75c929587e8104c4ff2a->block_body(Array, Array)
#16 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/f6/f6080ec4676190aa4332b33ccca8125c75c5e46dbd3ef8ff2fe23db77505e266.php(57): Twig_Template->displayBlock('body', Array, Array)
#17 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_6698ca38a3ac8afdea5e6883b56cae32213fa62603febb80362d4134a6af41f3->doDisplay(Array, Array)
#18 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#19 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#21 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/e5/e5dacc1ecbb1bd2c6405da40af4794e0630ec05bfc843690363847d663aff526.php(40): craft\web\twig\Template->display(Array, Array)
#22 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_e777137611a6a12df09dad0d58d66af74416fd7f1b7a246eb88f7075c059d56c->doDisplay(Array, Array)
#23 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#24 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#26 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/b5/b586f7910f5dd6690e36453b733d83cb359c13791dc83504a02a1402a257a42d.php(94): craft\web\twig\Template->display(Array, Array)
#27 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_18c937ced3dc4a1acf73d70763ac8bf059e22c63ea3c75c929587e8104c4ff2a->doDisplay(Array, Array)
#28 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#29 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#30 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#31 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/aa/aa06f363b01016dacdfcc62edc483b4c71f395ebfa38eaba85148cf22ba2b628.php(58): craft\web\twig\Template->display(Array, Array)
#32 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_26a6c3edb6b0e5dad0b7516d25bacfaff9d495ceac0a74a0da9a95352048c038->doDisplay(Array, Array)
#33 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#34 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#35 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#36 /Users/bruker1/Lokale sider/mustasj/storage/runtime/compiled_templates/20/20f19189a39ec0a39f38524c942363b193ff82ed88585141ea7a1396f5538c96.php(37): craft\web\twig\Template->display(Array, Array)
#37 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_72414fe613bfd69cbef959d85751d8793f29e2bb6eee26a221200e9a5be3fbe1->doDisplay(Array, Array)
#38 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#39 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#40 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#41 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#42 /Users/bruker1/Lokale sider/mustasj/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#43 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('seomatic/settin...', Array)
#44 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('seomatic/settin...', Array)
#45 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate('seomatic/settin...', Array)
#46 /Users/bruker1/Lokale sider/mustasj/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(281): craft\web\Controller->renderTemplate('seomatic/settin...', Array)
#47 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionGlobal('general', NULL)
#48 /Users/bruker1/Lokale sider/mustasj/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#49 /Users/bruker1/Lokale sider/mustasj/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#50 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('global', Array)
#51 /Users/bruker1/Lokale sider/mustasj/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('global', Array)
#52 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('seomatic/settin...', Array)
#53 /Users/bruker1/Lokale sider/mustasj/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/settin...', Array)
#54 /Users/bruker1/Lokale sider/mustasj/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/bruker1/Lokale sider/mustasj/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#56 /Users/bruker1/Lokale sider/mustasj/web/index.php(21): yii\base\Application->run()
#57 {main}
```

**Comment by khalwat** [comment]
So this ends up being a conflict between the CP Clear Cache plugin and SEOmatic, as discussed here:

https://github.com/mmikkel/CpClearCache-Craft/issues/1
