### ISSUE TITLE
Unable to create single called 'Register' unless SEOmatic is disabled

### ISSUE THREAD

**Issue by j-greig** [nystudio107/craft-seomatic#422]
Kept getting the generic error page when trying to create a new Single called "Register".

When I disabled SEOmatic I was able to create the single just fine.

Possible bug? Or am I doing something I shouldn't be?

Thanks :)

Craft v3.1.27
SEOmatic v3.1.50

```storage/logs$ cat web.log
2019-06-12 12:27:49 [-][1][2pqe9t4k0jejomvn72d04nhu9h][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 0 in /home/forge/www.client.com/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php:183
Stack trace:
#0 /home/forge/www.client.com/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/www...', 183)
#1 /home/forge/www.client.com/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php(183): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/www...', 183, Array)
#2 /home/forge/www.client.com/vendor/nystudio107/craft-seomatic/src/Seomatic.php(502): nystudio107\seomatic\services\Sitemaps->submitSitemapIndex()
#3 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(craft\events\SectionEvent))
#4 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\SectionEvent))
#5 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveSectio...', Object(craft\events\SectionEvent))
#6 /home/forge/www.client.com/vendor/craftcms/cms/src/services/Sections.php(783): yii\base\Component->trigger('afterSaveSectio...', Object(craft\events\SectionEvent))
#7 /home/forge/www.client.com/vendor/craftcms/cms/src/services/ProjectConfig.php(884): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#8 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#9 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#10 /home/forge/www.client.com/vendor/craftcms/cms/src/services/ProjectConfig.php(577): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#11 /home/forge/www.client.com/vendor/craftcms/cms/src/services/ProjectConfig.php(421): craft\services\ProjectConfig->processConfigChanges('sections.756e45...', true)
#12 /home/forge/www.client.com/vendor/craftcms/cms/src/services/Sections.php(498): craft\services\ProjectConfig->set('sections.756e45...', Array)
#13 /home/forge/www.client.com/vendor/craftcms/cms/src/controllers/SectionsController.php(186): craft\services\Sections->saveSection(Object(craft\models\Section))
#14 [internal function]: craft\controllers\SectionsController->actionSaveSection()
#15 /home/forge/www.client.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /home/forge/www.client.com/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-section', Array)
#18 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-section', Array)
#19 /home/forge/www.client.com/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('sections/save-s...', Array)
#20 /home/forge/www.client.com/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('sections/save-s...', Array)
#21 /home/forge/www.client.com/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /home/forge/www.client.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /home/forge/www.client.com/web/index.php(21): yii\base\Application->run()
#24 {main}
2019-06-12 12:27:49 [-][1][2pqe9t4k0jejomvn72d04nhu9h][info][application] $_GET = []
```

**Comment by khalwat** [comment]
Can you try updating to the latest version of SEOmatic before we get further into this? It's at 3.2.7 currently.

**Comment by khalwat** [comment]
So based on the line of code that we're at -- I'm guessing you have a site group that has no sites in it?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/0ed27b55e21f1da28e0c6dd80ec0f899fc8f232f
