### ISSUE TITLE
Object of class nystudio107\seomatic\models\MetaGlobalVars could not be converted to string

### ISSUE THREAD

**Issue by amityweb** [nystudio107/craft-seomatic#471]
Bit of a strange issue...

This page returns an error 500:
https://www.flintec.com/nz/weight-sensors/load-cells/single-point/pc2

This page exists on other languages and is a template page for products. Here is the UK one which should be identical apart from links to uk instead of nz:
https://www.flintec.com/uk/weight-sensors/load-cells/single-point/pc2

I re-saved it last night and it worked, but the error is back. 

The logs show an error for SEOMatic:

```
2019-09-20 09:06:04 [-][-][-][error][yii\base\ErrorException:4096] yii\base\ErrorException: Object of class nystudio107\seomatic\models\MetaGlobalVars could not be converted to string in /home/myaccount/craftcms/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php:269
Stack trace:
#0 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(4096, 'Object of class...', '/home/myaccount/...', 269)
#1 /home/myaccount/craftcms/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(269): craft\web\ErrorHandler->handleError(4096, 'Object of class...', '/home/myaccount/...', 269, Array)
#2 /home/myaccount/craftcms/vendor/nystudio107/craft-seomatic/src/Seomatic.php(645): nystudio107\seomatic\services\MetaContainers->includeScriptBodyHtml(2)
#3 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#4 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#5 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'beginBody', Object(yii\base\Event))
#6 /home/myaccount/craftcms/vendor/yiisoft/yii2/web/View.php(150): yii\base\Component->trigger('beginBody')
#7 /home/myaccount/craftcms/storage/runtime/compiled_templates/87/877214bcfb25d85fb516afa0127f918e4e7d198913272af84cec7ab1256d548d.php(59): yii\web\View->beginBody()
#8 /home/myaccount/craftcms/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6a864f9c35f6917493b803a713361adbebb5a9f2554f556a3911ed07af1d2807->doDisplay(Array, Array)
#9 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /home/myaccount/craftcms/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#12 /home/myaccount/craftcms/storage/runtime/compiled_templates/fb/fb402be905a0be092f0d95f3bb5966f69d48a0641279c2661e996ef40f574410.php(55): craft\web\twig\Template->display(Array, Array)
#13 /home/myaccount/craftcms/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9f5fa42aab8c6430a2f95d3d0a5bdfa47a0de8d2ef114029a3ff6ab879af318b->doDisplay(Array, Array)
#14 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /home/myaccount/craftcms/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#17 /home/myaccount/craftcms/vendor/twig/twig/src/Template.php(392): craft\web\twig\Template->display(Array)
#18 /home/myaccount/craftcms/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#19 /home/myaccount/craftcms/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#20 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('shop/products/_...', Array)
#21 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('shop/products/_...', Array)
#22 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('shop/products/_...', Array)
#23 /home/myaccount/craftcms/vendor/craftcms/cms/src/controllers/TemplatesController.php(95): craft\web\Controller->renderTemplate('shop/products/_...', Array)
#24 [internal function]: craft\controllers\TemplatesController->actionRender('shop/products/_...', Array)
#25 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#27 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#28 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#29 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#30 /home/myaccount/craftcms/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#31 /home/myaccount/craftcms/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#32 /home/myaccount/craftcms/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /home/myaccount/public_html/index.php(23): yii\base\Application->run()
#34 {main}
2019-09-20 09:06:04 [-][-][-][info][application] $_GET = [
    'p' => 'nz/weight-sensors/load-cells/single-point/pc2'
]
```

**Comment by amityweb** [comment]
Debugging your code, I can see $script is an object not a string, and this is the Object below. 

The thing is, the data in this object below is NOT the correct data for the page I am on. But its similar. I am on page with slug pc2, but this data below is for a different product, with slug pc22. 

Another page with this issue is slug pc1, but its outputting data for slug pc12. 

Could your code be fetching entries based on the slug containing the slug for the page and not an exact match? 

$script is blank when on a page without this issue.  

$script is outputting as this which is a different page's data, and being an object cannot echo and so errors:

```
Object
(
    [language] => en-us
    [mainEntityOfPage] => Product
    [seoTitle] => Flintec PC22 Single Point Load Cell
    [siteNamePosition] => none
    [seoDescription] => 
    [seoKeywords] => 
    [seoImage] => 
    [seoImageWidth] => 
    [seoImageHeight] => 
    [seoImageDescription] => 
    [canonicalUrl] => https://www.flintec.com/weight-sensors/load-cells/single-point/pc22
    [robots] => all
    [ogType] => website
    [ogTitle] => Flintec PC22 Single Point Load Cell
    [ogSiteNamePosition] => none
    [ogDescription] => {seomatic.meta.seoDescription}
    [ogImage] => 
    [ogImageWidth] => 
    [ogImageHeight] => 
    [ogImageDescription] => {seomatic.meta.seoImageDescription}
    [twitterCard] => summary_large_image
    [twitterCreator] => flintec
    [twitterTitle] => Flintec PC22 Single Point Load Cell
    [twitterSiteNamePosition] => none
    [twitterDescription] => {seomatic.meta.seoDescription}
    [twitterImage] => 
    [twitterImageWidth] => 
    [twitterImageHeight] => 
    [twitterImageDescription] => {seomatic.meta.seoImageDescription}
    [_errors:yii\base\Model:private] => 
    [_validators:yii\base\Model:private] => ArrayObject Object
        (
            [storage:ArrayObject:private] => Array
                (
                    [0] => yii\validators\StringValidator Object
                        (
                            [length] => 
                            [max] => 
                            [min] => 
                            [message] => {attribute} must be a string.
                            [tooShort] => 
                            [tooLong] => 
                            [notEqual] => 
                            [encoding] => UTF-8
                            [attributes] => Array
                                (
                                    [0] => language
                                    [1] => mainEntityOfPage
                                    [2] => seoTitle
                                    [3] => siteNamePosition
                                    [4] => seoDescription
                                    [5] => seoKeywords
                                    [6] => seoImage
                                    [7] => seoImageWidth
                                    [8] => seoImageHeight
                                    [9] => seoImageDescription
                                    [10] => robots
                                    [11] => ogType
                                    [12] => ogTitle
                                    [13] => ogSiteNamePosition
                                    [14] => ogDescription
                                    [15] => ogImage
                                    [16] => ogImageWidth
                                    [17] => ogImageHeight
                                    [18] => ogImageDescription
                                    [19] => twitterCard
                                    [20] => twitterCreator
                                    [21] => twitterTitle
                                    [22] => twitterSiteNamePosition
                                    [23] => twitterDescription
                                    [24] => twitterImage
                                    [25] => twitterImageHeight
                                    [26] => twitterImageWidth
                                    [27] => twitterImageDescription
                                    [28] => canonicalUrl
                                )

                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                    [1] => yii\validators\RangeValidator Object
                        (
                            [range] => Array
                                (
                                    [0] => summary
                                    [1] => summary_large_image
                                    [2] => app
                                    [3] => player
                                )

                            [strict] => 
                            [not] => 
                            [allowArray] => 
                            [attributes] => Array
                                (
                                    [0] => twitterCard
                                )

                            [message] => {attribute} is invalid.
                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                    [2] => yii\validators\RangeValidator Object
                        (
                            [range] => Array
                                (
                                    [0] => all
                                    [1] => index
                                    [2] => noindex
                                    [3] => follow
                                    [4] => nofollow
                                    [5] => none
                                    [6] => noodp
                                    [7] => noarchive
                                    [8] => nosnippet
                                    [9] => noimageindex
                                    [10] => nocache
                                )

                            [strict] => 
                            [not] => 
                            [allowArray] => 
                            [attributes] => Array
                                (
                                    [0] => robots
                                )

                            [message] => {attribute} is invalid.
                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                )

        )

    [_scenario:yii\base\Model:private] => default
    [_events:yii\base\Component:private] => Array
        (
        )

    [_eventWildcards:yii\base\Component:private] => Array
        (
        )

    [_behaviors:yii\base\Component:private] => Array
        (
        )

)
nystudio107\seomatic\models\MetaSiteVars Object
(
    [siteName] => Flintec
    [identity] => nystudio107\seomatic\models\Entity Object
        (
            [siteType] => Organization
            [siteSubType] => LocalBusiness
            [siteSpecificType] => 
            [computedType] => Organization
            [genericName] => 
            [genericAlternateName] => 
            [genericDescription] => 
            [genericUrl] => 
            [genericImage] => 
            [genericImageWidth] => 
            [genericImageHeight] => 
            [genericImageIds] => Array
                (
                )

            [genericTelephone] => 
            [genericEmail] => 
            [genericStreetAddress] => 
            [genericAddressLocality] => 
            [genericAddressRegion] => 
            [genericPostalCode] => 
            [genericAddressCountry] => 
            [genericGeoLatitude] => 
            [genericGeoLongitude] => 
            [personGender] => 
            [personBirthPlace] => 
            [organizationDuns] => 
            [organizationFounder] => 
            [organizationFoundingDate] => 
            [organizationFoundingLocation] => 
            [organizationContactPoints] => Array
                (
                )

            [corporationTickerSymbol] => 
            [localBusinessPriceRange] => 
            [localBusinessOpeningHours] => Array
                (
                )

            [restaurantServesCuisine] => 
            [restaurantMenuUrl] => 
            [restaurantReservationsUrl] => 
            [_errors:yii\base\Model:private] => 
            [_validators:yii\base\Model:private] => 
            [_scenario:yii\base\Model:private] => default
            [_events:yii\base\Component:private] => Array
                (
                )

            [_eventWildcards:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => Array
                (
                )

        )

    [creator] => nystudio107\seomatic\models\Entity Object
        (
            [siteType] => Organization
            [siteSubType] => LocalBusiness
            [siteSpecificType] => 
            [computedType] => Organization
            [genericName] => 
            [genericAlternateName] => 
            [genericDescription] => 
            [genericUrl] => 
            [genericImage] => 
            [genericImageWidth] => 
            [genericImageHeight] => 
            [genericImageIds] => Array
                (
                )

            [genericTelephone] => 
            [genericEmail] => 
            [genericStreetAddress] => 
            [genericAddressLocality] => 
            [genericAddressRegion] => 
            [genericPostalCode] => 
            [genericAddressCountry] => 
            [genericGeoLatitude] => 
            [genericGeoLongitude] => 
            [personGender] => 
            [personBirthPlace] => 
            [organizationDuns] => 
            [organizationFounder] => 
            [organizationFoundingDate] => 
            [organizationFoundingLocation] => 
            [organizationContactPoints] => Array
                (
                )

            [corporationTickerSymbol] => 
            [localBusinessPriceRange] => 
            [localBusinessOpeningHours] => Array
                (
                )

            [restaurantServesCuisine] => 
            [restaurantMenuUrl] => 
            [restaurantReservationsUrl] => 
            [_errors:yii\base\Model:private] => 
            [_validators:yii\base\Model:private] => 
            [_scenario:yii\base\Model:private] => default
            [_events:yii\base\Component:private] => Array
                (
                )

            [_eventWildcards:yii\base\Component:private] => Array
                (
                )

            [_behaviors:yii\base\Component:private] => Array
                (
                )

        )

    [twitterHandle] => flintec
    [facebookProfileId] => 
    [facebookAppId] => 
    [googleSiteVerification] => 
    [bingSiteVerification] => 
    [pinterestSiteVerification] => 
    [sameAsLinks] => Array
        (
            [twitter] => Array
                (
                    [siteName] => Twitter
                    [handle] => twitter
                    [url] => 
                )

            [facebook] => Array
                (
                    [siteName] => Facebook
                    [handle] => facebook
                    [url] => 
                )

            [wikipedia] => Array
                (
                    [siteName] => Wikipedia
                    [handle] => wikipedia
                    [url] => 
                )

            [linkedin] => Array
                (
                    [siteName] => LinkedIn
                    [handle] => linkedin
                    [url] => 
                )

            [googleplus] => Array
                (
                    [siteName] => Google+
                    [handle] => googleplus
                    [url] => 
                )

            [youtube] => Array
                (
                    [siteName] => YouTube
                    [handle] => youtube
                    [url] => 
                )

            [instagram] => Array
                (
                    [siteName] => Instagram
                    [handle] => instagram
                    [url] => 
                )

            [pinterest] => Array
                (
                    [siteName] => Pinterest
                    [handle] => pinterest
                    [url] => 
                )

            [github] => Array
                (
                    [siteName] => GitHub
                    [handle] => github
                    [url] => 
                )

            [vimeo] => Array
                (
                    [siteName] => Vimeo
                    [handle] => vimeo
                    [url] => 
                )

        )

    [siteLinksSearchTarget] => 
    [siteLinksQueryInput] => 
    [additionalSitemapUrls] => 
    [additionalSitemapUrlsDateUpdated] => 
    [additionalSitemaps] => 
    [_errors:yii\base\Model:private] => 
    [_validators:yii\base\Model:private] => ArrayObject Object
        (
            [storage:ArrayObject:private] => Array
                (
                    [0] => yii\validators\StringValidator Object
                        (
                            [length] => 
                            [max] => 
                            [min] => 
                            [message] => {attribute} must be a string.
                            [tooShort] => 
                            [tooLong] => 
                            [notEqual] => 
                            [encoding] => UTF-8
                            [attributes] => Array
                                (
                                    [0] => siteName
                                    [1] => twitterHandle
                                    [2] => facebookProfileId
                                    [3] => facebookAppId
                                    [4] => googleSiteVerification
                                    [5] => bingSiteVerification
                                    [6] => pinterestSiteVerification
                                    [7] => siteLinksSearchTarget
                                    [8] => siteLinksQueryInput
                                )

                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                    [1] => craft\validators\DateTimeValidator Object
                        (
                            [attributes] => Array
                                (
                                    [0] => additionalSitemapUrlsDateUpdated
                                )

                            [message] => 
                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                    [2] => craft\validators\ArrayValidator Object
                        (
                            [count] => 
                            [max] => 
                            [min] => 
                            [tooFew] => 
                            [tooMany] => 
                            [notEqual] => 
                            [attributes] => Array
                                (
                                    [0] => sameAsLinks
                                    [1] => additionalSitemapUrls
                                    [2] => additionalSitemaps
                                )

                            [message] => {attribute} must be an array.
                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_eventWildcards:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )

                )

        )

    [_scenario:yii\base\Model:private] => default
    [_events:yii\base\Component:private] => Array
        (
        )

    [_eventWildcards:yii\base\Component:private] => Array
        (
        )

    [_behaviors:yii\base\Component:private] => Array
        (
        )

)

```

**Comment by amityweb** [comment]
It looks like the SEOMatic data like title and description are all output correct for the page, so it looks like its just fetching script data wrong when slugs semi-match others, and the script data is breaking it then as is not a string. 

I have added this to to the code as a temporary fix but I would imagine it needs a better solution, like fetching the correct page in the first place. 

`if(is_string($script)) echo $script;`

**Comment by khalwat** [comment]
What version of SEOmatic are you using here?

**Comment by khalwat** [comment]
So I think what is happening here is it's actually loading something other than the script container from the cache. I've fixed that, and also added some paranoid protections via

https://github.com/nystudio107/craft-seomatic/commit/7d99763880e64ffbb70d1def4e8cc56b77790397
