### ISSUE TITLE
Sitemap settings saving

### ISSUE THREAD

**Issue by umkasanki** [nystudio107/craft-seomatic#484]
Hello.
After saving my sitemap settings I get an error:

![изображение](https://user-images.githubusercontent.com/496132/66582148-f5e54100-eb89-11e9-9bfc-092c99095ec2.png)

Could you check the reason for it?
My Seomatic table:
[craft_seomatic_metabundles.sql.zip](https://github.com/nystudio107/craft-seomatic/files/3713279/craft_seomatic_metabundles.sql.zip)

Thanks

**Comment by khalwat** [comment]
Can you please give me a stack trace from the error? It should be in your `storage/logs/web.log`

**Comment by umkasanki** [comment]
[logs.zip](https://github.com/nystudio107/craft-seomatic/files/3715792/logs.zip)

**Comment by khalwat** [comment]
Here's the error:

```
2019-10-10 17:04:51 [-][1][8aqdjutrnv88t0mboia69fdaoj55t185][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Extension\CoreExtension.php:524
Stack trace:
#0 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Array to string...', 'C:\\OSPanel\\doma...', 524)
#1 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Extension\CoreExtension.php(524): craft\web\ErrorHandler->handleError(8, 'Array to string...', 'C:\\OSPanel\\doma...', 524, Array)
#2 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\20\20a99941cd23df085e79aa4d4fcb0c5d305c5aa6611e84361d272499df428282.php(42): twig_date_converter(Object(craft\web\twig\Environment), Array, false)
#3 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_52aa75c1903ab0c295f833fcb67f906bd53726d0e5dbd1bd34299e70f98e5db3->doDisplay(Array, Array)
#4 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#5 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\06\061c62568419515a4455fa17e5c382ff96b6852bbf62008b08eb8d4cce3910d9.php(381): Twig\Template->display(Array)
#6 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(184): __TwigTemplate_ccddaf1c3a9979d2b4f7d4849f9260f998f3c5e34d5157912739a05576390714->block_tablecell(Array, Array)
#7 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\06\061c62568419515a4455fa17e5c382ff96b6852bbf62008b08eb8d4cce3910d9.php(241): Twig\Template->displayBlock('tablecell', Array, Array)
#8 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_ccddaf1c3a9979d2b4f7d4849f9260f998f3c5e34d5157912739a05576390714->doDisplay(Array, Array)
#9 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#10 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\f2\f22f9f7a5cfde7c8db8babdd4cac2b7b043270a79beeeccfb65d1d4e63d0f0bd.php(1383): Twig\Template->display(Array)
#11 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Extension\CoreExtension.php(1105): __TwigTemplate_bffb72ef45c25b3795886082bd093de3b8b2ec84a46e8fb6eeaead53a349d800->macro_editableTableField(Array)
#12 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\55\55c538cbbe7e60bea0f9ea5681e73a3004e1a2ba1e49f2ade8b9ef6f86c5c8bf.php(71): twig_call_macro(Object(__TwigTemplate_bffb72ef45c25b3795886082bd093de3b8b2ec84a46e8fb6eeaead53a349d800), 'macro_editableT...', Array, 14, Array, Object(Twig\Source))
#13 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_af8a361633bd3374148d54d82349ab8a1015cd7b9fbf645b58cc2270f60a9b3d->doDisplay(Array, Array)
#14 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\96\9637b5e466664dc1ad126c1e4c46b7d2f093ee429912ddfbc21844e1c3b93527.php(133): Twig\Template->display(Array)
#16 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(184): __TwigTemplate_4c8aa243df194cbafac0d7002e1e6777f88cf5feae254ca8548c0f2f796f24bb->block_content(Array, Array)
#17 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\b6\b607d8e90ae295074e97022e26b3cd7a2d7f45802a9496bb1daaa397776c6035.php(727): Twig\Template->displayBlock('content', Array, Array)
#18 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(184): __TwigTemplate_e05ba7a8f3565428e3ac7e50a76582627a2cd1e27af714c57c243c464fbeaea5->block_main(Array, Array)
#19 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\b6\b607d8e90ae295074e97022e26b3cd7a2d7f45802a9496bb1daaa397776c6035.php(576): Twig\Template->displayBlock('main', Array, Array)
#20 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(184): __TwigTemplate_e05ba7a8f3565428e3ac7e50a76582627a2cd1e27af714c57c243c464fbeaea5->block_body(Array, Array)
#21 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\55\55fcfcf8cc85e8bc88924cdb52a53f279dcbd6791748e57c598a5a51fdbb9676.php(75): Twig\Template->displayBlock('body', Array, Array)
#22 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_23d6f4862ba06cf0c338eb269e845e3d29f92fc0452ee23395bbe7b037c6de94->doDisplay('[<span class="s...', Array)
#23 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#24 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\ea\ea1785379ee990faa70eb1dfaa2061d8a4171addb0ad261ed573231a695b3760.php(56): Twig\Template->display(Array, Array)
#25 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_6d6f4081c9fd48e5f96f47ff7e32a5decca9c757e97bb6ef82d82126d943d7da->doDisplay(Array, Array)
#26 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#27 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\b6\b607d8e90ae295074e97022e26b3cd7a2d7f45802a9496bb1daaa397776c6035.php(118): Twig\Template->display(Array, Array)
#28 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_e05ba7a8f3565428e3ac7e50a76582627a2cd1e27af714c57c243c464fbeaea5->doDisplay(Array, Array)
#29 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#30 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\13\136176276e69199dddadc90ba1ff514b2d79f817125c4fadfa1d9e057996682e.php(48): Twig\Template->display(Array, Array)
#31 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_e5cb0fdf25a5f70ae6535970e2add034a22c49d9095835b3c148d2f6e24be00f->doDisplay(Array, Array)
#32 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#33 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\6b\6b030d01c1f8ae81d96af5249e322426da790cb868c5db70ab7fae805dffa585.php(78): Twig\Template->display(Array, Array)
#34 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_718511409e3b0194f7ff117f2714de2e18cdf73ccd42371bd023594492efd6c1->doDisplay(Array, Array)
#35 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#36 C:\OSPanel\domains\simplicate2\storage\runtime\compiled_templates\96\9637b5e466664dc1ad126c1e4c46b7d2f093ee429912ddfbc21844e1c3b93527.php(49): Twig\Template->display(Array, Array)
#37 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(407): __TwigTemplate_4c8aa243df194cbafac0d7002e1e6777f88cf5feae254ca8548c0f2f796f24bb->doDisplay(Array, Array)
#38 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#39 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Template.php(392): Twig\Template->display(Array)
#40 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#41 C:\OSPanel\domains\simplicate2\vendor\twig\twig\src\Environment.php(318): Twig\TemplateWrapper->render(Array)
#42 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\View.php(344): Twig\Environment->render('seomatic/settin...', Array)
#43 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\View.php(393): craft\web\View->renderTemplate('seomatic/settin...', '[<span class="s...')
#44 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\Controller.php(243): craft\web\View->renderPageTemplate('seomatic/settin...', '[<span class="s...')
#45 C:\OSPanel\domains\simplicate2\vendor\nystudio107\craft-seomatic\src\controllers\SettingsController.php(670): craft\web\Controller->renderTemplate('seomatic/settin...', Array)
#46 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionSite('sitemap', 'default')
#47 C:\OSPanel\domains\simplicate2\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#48 C:\OSPanel\domains\simplicate2\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#49 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\Controller.php(187): yii\base\Controller->runAction('site', Array)
#50 C:\OSPanel\domains\simplicate2\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('site', Array)
#51 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\Application.php(299): yii\base\Module->runAction('seomatic/settin...', Array)
#52 C:\OSPanel\domains\simplicate2\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('seomatic/settin...', Array)
#53 C:\OSPanel\domains\simplicate2\vendor\craftcms\cms\src\web\Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#54 C:\OSPanel\domains\simplicate2\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#55 C:\OSPanel\domains\simplicate2\web\index.php(21): yii\base\Application->run()
#56 {main}
2019-10-10 17:04:50 [-][1][8aqdjutrnv88t0mboia69fdaoj55t185][info][application] $_GET = [
    'p' => 'craft-admin/seomatic/site/sitemap/default'
]
```

**Comment by khalwat** [comment]
It's a bit hard to tell from the error logs, but it _appears_ to be complaining about rendering something that's in one of the two Table Cells that's on that page.

Can you show me a screenshot of the SEOmatic -> Site Settings -> Sitemap page in your browser @umkasanki ?

**Comment by umkasanki** [comment]
After this error occurred, the page no longer opened in the browser. 
Instead of a page, I saw a bug report.
Because the client could not wait long, I was writing to restore the database from a backup. Now the site is working fine.
I decided to inform you about it just in case
