### ISSUE TITLE
Malformed UTF-8 characters error when encoding JSON-LD

### ISSUE THREAD

**Issue by drifteaur** [nystudio107/craft-seomatic#628]
Craft Pro 3.4.17.1
SEOmatic | 3.3.1

I'm getting the following error from SEOMatic when viewing some entries on the frontend. Tried to find what string could be causing trouble, but the json-ld $value array is really big, it's hard to find the offending string.

```
An Error occurred while handling another error:
yii\base\InvalidArgumentException:  UTF-8 characters, possibly incorrectly encoded. in /var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php:133
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\helpers\BaseJson::handleJsonError(5)
#1 /var/www/html/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(74): yii\helpers\BaseJson::encode(Array, 449)
#2 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php(272): nystudio107\seomatic\helpers\JsonLd::encode(Object(nystudio107\seomatic\models\jsonld\NGO))
#3 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(75): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#4 [internal function]: nystudio107\seomatic\models\MetaJsonLdContainer->nystudio107\seomatic\models\{closure}(Object(yii\caching\FileCache))
#5 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#6 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(101): yii\caching\Cache->getOrSet('MetaJsonLdConta...', Object(Closure), 30, Object(yii\caching\TagDependency))
#7 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(301): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#8 /var/www/html/vendor/nystudio107/craft-seomatic/src/Seomatic.php(758): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#9 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#10 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#11 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#12 /var/www/html/vendor/yiisoft/yii2/web/View.php(175): yii\base\Component->trigger('endPage')
#13 /var/www/html/vendor/craftcms/cms/src/web/View.php(1576): yii\web\View->endPage(false)
#14 /var/www/html/vendor/yiisoft/yii2/views/errorHandler/exception.php(544): craft\web\View->endPage()
#15 /var/www/html/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/v...')
#16 /var/www/html/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/v...', Array)
#17 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/var/www/html/v...', Array, Object(craft\web\ErrorHandler))
#18 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(128): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidArgumentException))
#20 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(123): craft\web\ErrorHandler->renderException(Object(yii\base\InvalidArgumentException))
#21 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(61): yii\base\ErrorHandler->handleException(Object(yii\base\InvalidArgumentException))
#22 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\InvalidArgumentException))
#23 {main}
Previous exception:
yii\base\InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded. in /var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php:133
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\helpers\BaseJson::handleJsonError(5)
#1 /var/www/html/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(74): yii\helpers\BaseJson::encode(Array, 449)
#2 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php(272): nystudio107\seomatic\helpers\JsonLd::encode(Object(nystudio107\seomatic\models\jsonld\NGO))
#3 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(75): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#4 [internal function]: nystudio107\seomatic\models\MetaJsonLdContainer->nystudio107\seomatic\models\{closure}(Object(yii\caching\FileCache))
#5 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#6 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(101): yii\caching\Cache->getOrSet('MetaJsonLdConta...', Object(Closure), 30, Object(yii\caching\TagDependency))
#7 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(301): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#8 /var/www/html/vendor/nystudio107/craft-seomatic/src/Seomatic.php(758): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#9 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#10 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#11 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#12 /var/www/html/vendor/yiisoft/yii2/web/View.php(175): yii\base\Component->trigger('endPage')
#13 /var/www/html/vendor/craftcms/cms/src/web/View.php(1576): yii\web\View->endPage(false)
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(459): craft\web\View->endPage()
#15 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('page/_entry', Array, 'site')
#16 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('page/_entry', Array)
#17 [internal function]: craft\controllers\TemplatesController->actionRender('page/_entry', Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#21 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#23 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#25 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /var/www/html/web/index.php(62): yii\base\Application->run()
#27 {main}
```

**Comment by khalwat** [comment]
The error being thrown here is actually being thrown by Yii2, not SEOmatic. And indeed, it is likely that some data is improperly encoded.

I've added a try/catch to handle the exception in this case:

https://github.com/nystudio107/craft-seomatic/commit/688cb45e7b0cdd2c932da4abb0be8b6ca2b70963

You can try it now by setting your semver to: `dev-develop`
