### ISSUE TITLE
Column not found: 1054 Unknown column 'typeId' in 'where clause'

### ISSUE THREAD

**Issue by engram-design** [nystudio107/craft-seomatic#635]
When upgrading from:

- SEOmatic 3.2.47
- Craft 3.3.19

to

- SEOmatic 3.3.3 (latest)
- Craft 3.4.19 (latest)

I get the following error when running `./craft migrate/all`.

```
Joshs-MacBook-Pro:site joshcrawford$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.35)

    > dropping {{%projectconfig}} if it exists ... done (time: 0.006s)
    > create table {{%projectconfig}} ... done (time: 0.014s)
    > batch insert into {{%projectconfig}} ... done (time: 0.005s)
    ....
    > batch insert into {{%projectconfig}} ... done (time: 0.002s)
    > batch insert into {{%projectconfig}} ... done (time: 0.001s)
    > drop column config from table {{%info}} ... done (time: 0.050s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'typeId' in 'where clause'
The SQL being executed was: SELECT *
FROM `seomatic_metabundles`
WHERE (`sourceBundleType`='section') AND (`sourceId`=1) AND (`sourceSiteId`=1) AND (`typeId` IS NULL)
LIMIT 1 (/Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT *\nFROM `...')
#1 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT *\nFROM `...')
#2 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(415): yii\db\Command->queryInternal('fetch', NULL)
#3 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Command->queryOne()
#4 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#5 /Users/joshcrawford/public_html/site/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(212): craft\db\Query->one()
#6 /Users/joshcrawford/public_html/site/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php(251): nystudio107\seomatic\services\MetaBundles->getMetaBundleBySourceId('section', 1, 1)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/base/Element.php(1416): nystudio107\seomatic\fields\SeoSettings->serializeValue(Object(nystudio107\seomatic\models\MetaBundle), Object(craft\elements\Entry))
#8 [internal function]: craft\base\Element->validateCustomFieldContentSize('seoMeta', NULL, Object(yii\validators\InlineValidator))
#9 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'seoMeta', NULL, Object(yii\validators\InlineValidator))
#10 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/validators/Validator.php(257): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'seoMeta')
#11 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#12 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Elements.php(1990): yii\base\Model->validate()
#13 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, NULL)
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Sections.php(1565): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#15 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Sections.php(775): craft\services\Sections->_ensureSingleEntry(Object(craft\models\Section), Array)
#16 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#17 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#18 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#19 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#20 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\ProjectConfig->processConfigChanges('sections.2e86d6...')
#21 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#22 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#23 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#24 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/ProjectConfig.php(489): craft\services\ProjectConfig->processConfigChanges('sections.2e86d6...', true, '')
#25 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.2e86d6...', Array)
#26 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#27 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#28 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#29 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#30 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#31 [internal function]: craft\console\controllers\MigrateController->actionAll()
#32 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#34 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#35 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#36 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#37 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#38 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#39 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#40 /Users/joshcrawford/public_html/site/craft(22): yii\base\Application->run()
#41 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Craft CMS.'

in /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php:241

Stack trace:
#0 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/joshcrawford/public_html/site/craft(22): yii\base\Application->run()
#11 {main}
```

**Comment by engram-design** [comment]
For the moment, disabling seomatic via:

```
'disabledPlugins' => [
    'seomatic',
],
```
will bypass this for the time being. I feel like its potentially a Craft core migration that's causing this, but probably should be handled by seomatic

**Comment by engram-design** [comment]
Another similar error, in the same place:
```
> batch insert into {{%projectconfig}} ... done (time: 0.002s)
> batch insert into {{%projectconfig}} ... done (time: 0.002s)
> batch insert into {{%projectconfig}} ... done (time: 0.002s)
> batch insert into {{%projectconfig}} ... done (time: 0.002s)
> drop column config from table {{%info}} ... done (time: 0.021s)
Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_seoMeta' at row 2
The SQL being executed was: ALTER TABLE `content` CHANGE `field_seoMeta` `field_seoMeta` varchar(255) (/home/forge/site/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /home/forge/site/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `co...')
#1 /home/forge/site/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `co...')
#2 /home/forge/site/vendor/craftcms/cms/src/services/Fields.php(1469): yii\db\Command->execute()
#3 /home/forge/site/vendor/craftcms/cms/src/services/Fields.php(826): craft\services\Fields->applyFieldSave('ea81602e-3059-4...', Array, 'global')
#4 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Fields->handleChangedField(Object(craft\events\ConfigEvent))
#5 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#6 /home/forge/site/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#7 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#8 /home/forge/site/vendor/craftcms/cms/src/helpers/ProjectConfig.php(64): craft\services\ProjectConfig->processConfigChanges('fields.ea81602e...')
#9 /home/forge/site/vendor/craftcms/cms/src/services/Sections.php(595): craft\helpers\ProjectConfig::ensureAllFieldsProcessed()
#10 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 /home/forge/site/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#14 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\ProjectConfig->processConfigChanges('sections.1f9b1b...')
#15 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#16 /home/forge/site/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#17 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#18 /home/forge/site/vendor/craftcms/cms/src/services/ProjectConfig.php(489): craft\services\ProjectConfig->processConfigChanges('sections.1f9b1b...', true, '')
#19 /home/forge/site/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.1f9b1b...', Array)
#20 /home/forge/site/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#21 /home/forge/site/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#22 /home/forge/site/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#23 /home/forge/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#24 /home/forge/site/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#25 [internal function]: craft\console\controllers\MigrateController->actionAll()
#26 /home/forge/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /home/forge/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /home/forge/site/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#29 /home/forge/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#30 /home/forge/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#31 /home/forge/site/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#32 /home/forge/site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#33 /home/forge/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#34 /home/forge/site/craft(22): yii\base\Application->run()
#35 {main}
```

**Comment by khalwat** [comment]
That's really interesting. So this is the migration that needs to be run:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/migrations/m200419_203444_add_type_id.php

I even go out of my way to not load up the "hooks" if SEOmatic has any pending migrations:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L398

From the stack trace, it looks like the Craft migration `m190913_152146_update_preview_targets` is forcing the issue by resaving field data... and if you have an SEOmatic field, it ends up calling this routine:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/fields/SeoSettings.php#L250

...which executes the query. Irony is that the code there I added for you, to fix up SEO Settings fields that had default values stored in them. :)

Shouldn't be too hard to add a conditional there to not execute that code path if migrations are pending.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/2929c2ef08396e770f51a55ffd67e5bfbf414ac2

**Comment by yordaa-me** [comment]
@khalwat 

Hi there, I am writing as I am seeing the same typeId error while visiting my homepage. I am not sure if this is related but here is what i am seeing.

<img width="1749" alt="Screenshot 2021-09-30 at 11 30 06" src="https://user-images.githubusercontent.com/29864680/135478995-5b1f6a61-54a4-4a46-8c61-83eeb9a79dfd.png">

### Our server Info: 
- SEOmatic: 3.4.15
- Craft Pro: 3.5.19.1
- Yii version: 2.0.38
- MySQL:  5.7.33

### What I tried to fix

I tried running `./craft migrate/all` and this returned successful saying all migration have been applied.

I then tried to downgrade and even redo the migration but had no luck as seen in the next screenshot.

I finally caved and created the `typeId` column within that table myself and it managed to remove the error. I'm not sure if this has even properly fixed things so if there is a proper fix out there, then please advise.

**Comment by khalwat** [comment]
I'm not sure exactly what went wrong in your case, but that migration should have be run. I'm not aware of any bugs in the code that would prevent it from running.

As long as you have the `typeId` column added, you should be good to go.
