### ISSUE TITLE
SQL error when updating Content SEO pages

### ISSUE THREAD

**Issue by csgrant83** [nystudio107/craft-seomatic#651]
I am getting the following error when trying to update any Content SEO page. No errors occur on any other pages within the plugin (e.g. I can update Global SEO without any issues).

Craft Pro 3.4.20
SEOmatic 3.3.4

PHP 7.2.24
PostgreSQL 10.12
Yii 2.0.35

`Database Exception – yii\db\Exception
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
The SQL being executed was: SELECT *
FROM "seomatic_metabundles"
WHERE ("sourceBundleType"='section') AND ("sourceHandle"='home') AND ("sourceSiteId"=1) AND ("typeId"='')
LIMIT 1
Error Info: Array
(
    [0] => 22P02
    [1] => 7
    [2] => ERROR:  invalid input syntax for integer: ""
)
↵
Caused by: PDOException
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""
in /var/www/staging.mroelectronics.com/html/craft/vendor/yiisoft/yii2/db/Command.php at line 1293`

**Comment by timmyomahony** [comment]
Also seeing this error

```
2020-05-26 19:41:15 [-][1][1e4j3ifmsglo1ngiqk7fjrg3hg][error][yii\db\Exception] PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "" in /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute()
#2 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(415): yii\db\Command->queryInternal()
#3 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Command->queryOne()
#4 /home/forge/mysite.com/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#5 /home/forge/mysite.com/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(273): craft\db\Query->one()
#6 /home/forge/mysite.com/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(593): nystudio107\seomatic\services\MetaBundles->getMetaBundleBySourceHandle()
#7 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionSaveContent()
#8 /home/forge/mysite.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#10 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#11 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#12 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#13 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#14 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#15 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#16 /home/forge/mysite.com/web/index.php(21): yii\base\Application->run()
#17 {main}
Next yii\db\Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: ""
The SQL being executed was: SELECT *
FROM "seomatic_metabundles"
WHERE ("sourceBundleType"='section') AND ("sourceHandle"='aboutUsPage') AND ("sourceSiteId"=2) AND ("typeId"='')
LIMIT 1 in /home/forge/mysite.com/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException()
#1 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute()
#2 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php(415): yii\db\Command->queryInternal()
#3 /home/forge/mysite.com/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Command->queryOne()
#4 /home/forge/mysite.com/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#5 /home/forge/mysite.com/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(273): craft\db\Query->one()
#6 /home/forge/mysite.com/vendor/nystudio107/craft-seomatic/src/controllers/SettingsController.php(593): nystudio107\seomatic\services\MetaBundles->getMetaBundleBySourceHandle()
#7 [internal function]: nystudio107\seomatic\controllers\SettingsController->actionSaveContent()
#8 /home/forge/mysite.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#10 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#11 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#12 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#13 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#14 /home/forge/mysite.com/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#15 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#16 /home/forge/mysite.com/web/index.php(21): yii\base\Application->run()
#17 {main}
Additional Information:
Array
(
    [0] => 22P02
    [1] => 7
    [2] => ERROR:  invalid input syntax for type integer: ""
)

2020-05-26 19:41:15 [-][1][1e4j3ifmsglo1ngiqk7fjrg3hg][info][application] $_GET = []

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'seomatic/settings/save-content'
    'siteId' => '2'
    'sourceHandle' => 'aboutUsPage'
    'sourceBundleType' => 'section'
    'typeId' => ''
    'redirect' => '6f5ac986a5fcf8594422dec8fb12fe4959c88cd65057abe9702478cebc663e68seomatic/edit-content/general/section/aboutUsPage/default?typeId='
    'metaBundleSettings' => [
        'siteType' => 'CreativeWork'
        'siteSubType' => 'WebPage'
        'siteSpecificType' => 'none'
        'seoTitleSource' => 'fromField'
        'seoTitleField' => 'title'
        'siteNamePositionSource' => 'sameAsGlobal'
        'seoDescriptionSource' => 'fromCustom'
        'seoDescriptionField' => 'title'
        'seoKeywordsSource' => 'fromCustom'
        'seoKeywordsField' => 'title'
        'seoImageSource' => 'fromAsset'
        'seoImageIds' => ''
        'seoImageTransform' => '1'
        'seoImageTransformMode' => 'crop'
        'ogImageSource' => 'sameAsSeo'
        'ogImageIds' => ''
        'ogImageTransform' => '1'
        'ogImageTransformMode' => 'crop'
        'twitterImageSource' => 'sameAsSeo'
        'twitterImageIds' => ''
        'twitterImageTransform' => '1'
        'twitterImageTransformMode' => 'crop'
        'seoImageDescriptionSource' => 'fromCustom'
        'seoImageDescriptionField' => 'title'
    ]
    'metaGlobalVars' => [
        'seoTitle' => '{entry.title}'
        'siteNamePosition' => 'before'
        'seoDescription' => ''
        'seoKeywords' => ''
        'seoImage' => ''
        'ogImage' => '{seomatic.meta.seoImage}'
        'twitterCard' => 'summary_large_image'
        'twitterImage' => '{seomatic.meta.seoImage}'
        'seoImageDescription' => ''
        'robots' => 'all'
        'canonicalUrl' => '{entry.url}'
    ]
]
```

The relevent section seems to be

```
The SQL being executed was: SELECT *
FROM "seomatic_metabundles"
WHERE ("sourceBundleType"='section') AND ("sourceHandle"='aboutUsPage') AND ("sourceSiteId"=2) AND ("typeId"='')
LIMIT 1 in /home/forge/mysite.com/vendor/yiisoft/yii2/db/Schema.php:674
```

I would guess this `("typeId"='')` should be an integer? 

This happens when saving a content page, e.g.

https://mysite.com/admin/seomatic/edit-content/general/section/aboutUsPage/default

Here's the post data:

```
CRAFT_CSRF_TOKEN=...
action=seomatic/settings/save-content
siteId=2
sourceHandle=aboutUsPage
sourceBundleType=section
typeId
redirect=6f5ac986a5fcf8594422dec8fb12fe4959c88cd65057abe9702478cebc663e68seomatic/edit-content/general/section/aboutUsPage/default?typeId=
metaBundleSettings[siteType]=CreativeWork
metaBundleSettings[siteSubType]=WebPage
metaBundleSettings[siteSpecificType]=none
metaBundleSettings[seoTitleSource]=fromField
metaBundleSettings[seoTitleField]=title
metaGlobalVars[seoTitle]={entry.title}
metaBundleSettings[siteNamePositionSource]=sameAsGlobal
metaGlobalVars[siteNamePosition]=before
metaBundleSettings[seoDescriptionSource]=fromCustom
metaBundleSettings[seoDescriptionField]=title
metaGlobalVars[seoDescription]
metaBundleSettings[seoKeywordsSource]=fromCustom
metaBundleSettings[seoKeywordsField]=title
metaGlobalVars[seoKeywords]
metaBundleSettings[seoImageSource]=fromAsset
metaBundleSettings[seoImageIds]
metaGlobalVars[seoImage]
metaBundleSettings[seoImageTransform]=1
metaBundleSettings[seoImageTransformMode]=crop
metaBundleSettings[ogImageSource]=sameAsSeo
metaBundleSettings[ogImageIds]
metaGlobalVars[ogImage]={seomatic.meta.seoImage}
metaBundleSettings[ogImageTransform]=1
metaBundleSettings[ogImageTransformMode]=crop
metaGlobalVars[twitterCard]=summary_large_image
metaBundleSettings[twitterImageSource]=sameAsSeo
metaBundleSettings[twitterImageIds]
metaGlobalVars[twitterImage]={seomatic.meta.seoImage}
metaBundleSettings[twitterImageTransform]=1
metaBundleSettings[twitterImageTransformMode]=crop
metaBundleSettings[seoImageDescriptionSource]=fromCustom
metaBundleSettings[seoImageDescriptionField]=title
metaGlobalVars[seoImageDescription]
metaGlobalVars[robots]=all
metaGlobalVars[canonicalUrl]={entry.url}
```

Tried to clear caches as well as a downgrade to `3.3.3` but still giving a 500

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/122ef0d1361e6fe0786952f10270bc39b57f1c73
