### ISSUE TITLE
MetaValue::parseMetaString throwing Twig render errors

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#683]
I'm consistently getting errors logged when I have fields with "questionable" content in them.

For example: I have some plain text fields that get submitted from frontend users. It appears to be an escaping problem, as it occurs when quotes, braces, \n type characters are present.

When it happens, I get 2 errors logged:

```
Twig\\Error\\SyntaxError: Unexpected token \"name\" of value \"getting\" (\"end of print statement\" expected) in \"__string_template__806b1eb7135df3fdfc5b525593e8eee277f76cb130047d177e59d0d18ea86913\" at line 5. in /app/vendor/composer/twig/twig/src/TokenStream.php:76

Stack trace:
#0 /app/vendor/composer/twig/twig/src/Parser.php(143): Twig\\TokenStream->expect(4)
#1 /app/vendor/composer/twig/twig/src/Parser.php(98): Twig\\Parser->subparse(NULL, false)
#2 /app/vendor/composer/twig/twig/src/Environment.php(563): Twig\\Parser->parse(Object(Twig\\TokenStream))
#3 /app/vendor/composer/twig/twig/src/Environment.php(595): Twig\\Environment->parse(Object(Twig\\TokenStream))
#4 /app/vendor/composer/craftcms/cms/src/web/twig/Environment.php(60): Twig\\Environment->compileSource(Object(Twig\\Source))
#5 /app/vendor/composer/twig/twig/src/Environment.php(408): craft\\web\\twig\\Environment->compileSource(Object(Twig\\Source))
#6 /app/vendor/composer/twig/twig/src/Environment.php(381): Twig\\Environment->loadClass('__TwigTemplate_...', '__string_templa...', NULL)
#7 /app/vendor/composer/craftcms/cms/src/web/twig/Environment.php(41): Twig\\Environment->loadTemplate('__string_templa...', NULL)
#8 /app/vendor/composer/twig/twig/src/Environment.php(462): craft\\web\\twig\\Environment->loadTemplate('__string_templa...')
#9 /app/vendor/composer/craftcms/cms/src/web/View.php(591): Twig\\Environment->createTemplate('I got my Pursui...')
#10 /app/vendor/composer/nystudio107/craft-seomatic/src/helpers/MetaValue.php(275): craft\\web\\View->renderObjectTemplate('I got my Pursui...', Array, Array)
#11 /app/vendor/composer/nystudio107/craft-seomatic/src/helpers/MetaValue.php(100): nystudio107\\seomatic\\helpers\\MetaValue::parseMetaString('I got my Pursui...', true, true)
#12 /app/vendor/composer/nystudio107/craft-seomatic/src/helpers/MetaValue.php(143): nystudio107\\seomatic\\helpers\\MetaValue::parseString('I got my Pursui...', true, true, 4)
#13 /app/vendor/composer/nystudio107/craft-seomatic/src/helpers/JsonLd.php(119): nystudio107\\seomatic\\helpers\\MetaValue::parseArray(Array)
#14 /app/vendor/composer/nystudio107/craft-seomatic/src/helpers/JsonLd.php(86): nystudio107\\seomatic\\helpers\\JsonLd::normalizeJsonLdArray(Array, 4)
```

Followed by:

```
{
    "message": "Error rendering `I got my Pursuit 100 in a trade for a fishing reel. It is my first yak. When I first used it, I thought it to be very tippy. It constantly rocked side to side and I was nervous. But I knew it was me and I had to settle in. After about 30 minutes or so, I relaxed enough to settle it down. It was then that I realized this little boat can rock side to side safely and I had no issues with taking it fishing.\r\n\r\nI mounted on some Scotty rod holders and used a 10 pound downrigger cannon ball for an anchor with a 50ft rope. Loaded in my truck, I grabbed some drinks and headed for the water.\r\n\r\nThe draft is very shallow. I was paddling around in a low tide river with only 4 inches of water. I followed that little creek to the main river where I encountered whitecaps waves and the little boat did fine. After fishing a bit { and getting dragged across some oyster beds by a large redfish} I started the paddle home. Back into the main river, I had to cross against an incoming ocean tide. I never broke sweat wondering if I was going to get a salt bath.\r\n\r\nIn fact, I decided to put it to the test. I paddled up to a commercial crap trap and typically weigh about 30 pounds empty. I grabbed the buoy and started pulling the trap up and with the side of the boat facing the whitecaps, I managed to get the trap on the boat and not get wet. I moved the trap to the opposite side and slowly lowered it back down. This time, the whitecaps were hitting the bottom of the boat. The trap had about 40-50 crabs in it so it may have weighed about 45 pounds or so. The little boat took the side loads beautifully.\r\n\r\nI decided to paddle the 1/2 mile to the south Atlantic from that river. It was very choppy and rough, but I never got wet other than from the crossing the trap over the boat and paddle drops. Into the ocean a couple hundred yards, I turned back and went in safely.\r\n\r\n I also have been in rivers where alligators are a very common sight. If I were scared of the boat tipping, this is not the place to be. One gator, maybe 4ft swam along side of me for a long way. It was comical. The larger gators just laid on the river banks watching me pass.\r\n\r\n The only problem I have with the boat is neither the boat's of Pelican's fault. That redfish that dragged me across some oyster beds did it. Those sharp oyster shells, really scratched the bottom side. If it had been my bare skin, lots and lots of stitches would be needed. But, despite the heavy scratching, the boat still performs flawlessly and no leaks. \r\n\r\n I feel comfortable enough with it in every way except maybe should a large shark decide to taste it. That might not be so good.` -> Unexpected token \"name\" of value \"getting\" (\"end of print statement\" expected) in \"__string_template__806b1eb7135df3fdfc5b525593e8eee277f76cb130047d177e59d0d18ea86913\" at line 5. - I got my Pursuit 100 in a trade for a fishing reel. It is my first yak. When I first used it, I thought it to be very tippy. It constantly rocked side to side and I was nervous. But I knew it was me and I had to settle in. After about 30 minutes or so, I relaxed enough to settle it down. It was then that I realized this little boat can rock side to side safely and I had no issues with taking it fishing.\r\n\r\nI mounted on some Scotty rod holders and used a 10 pound downrigger cannon ball for an anchor with a 50ft rope. Loaded in my truck, I grabbed some drinks and headed for the water.\r\n\r\nThe draft is very shallow. I was paddling around in a low tide river with only 4 inches of water. I followed that little creek to the main river where I encountered whitecaps waves and the little boat did fine. After fishing a bit { and getting dragged across some oyster beds by a large redfish} I started the paddle home. Back into the main river, I had to cross against an incoming ocean tide. I never broke sweat wondering if I was going to get a salt bath.\r\n\r\nIn fact, I decided to put it to the test. I paddled up to a commercial crap trap and typically weigh about 30 pounds empty. I grabbed the buoy and started pulling the trap up and with the side of the boat facing the whitecaps, I managed to get the trap on the boat and not get wet. I moved the trap to the opposite side and slowly lowered it back down. This time, the whitecaps were hitting the bottom of the boat. The trap had about 40-50 crabs in it so it may have weighed about 45 pounds or so. The little boat took the side loads beautifully.\r\n\r\nI decided to paddle the 1/2 mile to the south Atlantic from that river. It was very choppy and rough, but I never got wet other than from the crossing the trap over the boat and paddle drops. Into the ocean a couple hundred yards, I turned back and went in safely.\r\n\r\n I also have been in rivers where alligators are a very common sight. If I were scared of the boat tipping, this is not the place to be. One gator, maybe 4ft swam along side of me for a long way. It was comical. The larger gators just laid on the river banks watching me pass.\r\n\r\n The only problem I have with the boat is neither the boat's of Pelican's fault. That redfish that dragged me across some oyster beds did it. Those sharp oyster shells, really scratched the bottom side. If it had been my bare skin, lots and lots of stitches would be needed. But, despite the heavy scratching, the boat still performs flawlessly and no leaks. \r\n\r\n I feel comfortable enough with it in every way except maybe should a large shark decide to taste it. That might not be so good.",
    "context": {
        "trace": [],
        "memory": 29689752,
        "category": "nystudio107\\seomatic\\helpers\\MetaValue::parseMetaString"
    },
    "level": 400,
    "level_name": "ERROR",
    "channel": "craftcms",
    "datetime": "2020-07-08T17:29:19.911843+00:00",
    "extra": {}
}
```

- Craft CMS 3.4.27
- SEOmatic 3.3.10

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4818d1c8ce2f2affb3f3a1f0760f99a098af3e77
