### ISSUE TITLE
Project config sync error: "Trying to get property 'generalEnabledFields' of non-object"

### ISSUE THREAD

**Issue by sjcallender** [nystudio107/craft-seomatic#688]
### Describe the bug
Running `./craft project-config/sync` when trying to migrate from one environment to another (develop to prod) is throwing an SEOmatic related error. This is a multi-site build.

Here's what's changing in the project.yaml (left is prod, right is develop): https://www.diffchecker.com/6xxidRnT
It all seems unrelated.

Here's the full error in console.log

````
2020-07-15 14:34:59 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to get property 'generalEnabledFields' of non-object in /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php:587
Stack trace:
#0 /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(587): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/stephenc...', 587, Array)
#1 /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(816): nystudio107\seomatic\services\MetaBundles->pruneFieldMetaBundleSettings(Object(nystudio107\seomatic\models\MetaBundle), 'seoOverride')
#2 /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(219): nystudio107\seomatic\services\MetaContainers->loadFieldMetaContainers()
#3 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#4 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#5 /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(211): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 30, Object(yii\caching\TagDependency))
#6 /Users/stephencallender/Projects/_sites/local-ch/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(53): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('/', '1')
#7 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/ExtensionSet.php(329): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#8 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/Environment.php(928): Twig\ExtensionSet->getGlobals()
#9 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/Environment.php(948): Twig\Environment->getGlobals()
#10 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/Template.php(380): Twig\Environment->mergeGlobals(Array)
#11 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#12 /Users/stephencallender/Projects/_sites/local-ch/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/web/View.php(527): Twig\TemplateWrapper->render(Array)
#14 /Users/stephencallender/Projects/_sites/local-ch/vendor/lewisjenkins/craft-dynamic-fields/src/fields/Dropdown.php(49): craft\web\View->renderString('{ "label":"Alab...', Array)
#15 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/base/Element.php(2705): lewisjenkins\craftdynamicfields\fields\Dropdown->normalizeValue('OH', Object(verbb\supertable\elements\SuperTableBlockElement))
#16 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/base/Element.php(2177): craft\base\Element->normalizeFieldValue('state')
#17 /Users/stephencallender/Projects/_sites/local-ch/vendor/verbb/super-table/src/fields/SuperTableField.php(719): craft\base\Element->getFieldValue('state')
#18 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Search.php(167): verbb\supertable\fields\SuperTableField->getSearchKeywords(Object(verbb\supertable\elements\db\SuperTableBlockQuery), Object(craft\elements\GlobalSet))
#19 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(2239): craft\services\Search->indexElementAttributes(Object(craft\elements\GlobalSet))
#20 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(2380): craft\services\Elements->_saveElementInternal(Object(craft\elements\GlobalSet), true, false)
#21 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(2178): craft\services\Elements->_propagateElement(Object(craft\elements\GlobalSet), Array, Object(craft\elements\GlobalSet))
#22 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\GlobalSet), false, true, true)
#23 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Globals.php(434): craft\services\Elements->saveElement(Object(craft\elements\GlobalSet), false)
#24 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Globals->handleChangedGlobalSet(Object(craft\events\ConfigEvent))
#25 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#26 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#27 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(678): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#28 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\ProjectConfig->processConfigChanges('globalSets.ee59...')
#29 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#30 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#31 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#32 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(1204): craft\services\ProjectConfig->processConfigChanges('globalSets.ee59...', false, NULL, true)
#33 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#34 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#35 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#36 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#38 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('sync', Array)
#39 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('sync', Array)
#40 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#41 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#42 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#43 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#44 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#45 /Users/stephencallender/Projects/_sites/local-ch/craft(22): yii\base\Application->run()
#46 {main}
````

### To reproduce

This is probably a site-specific issue, so I've sent the database, project.yaml, and composer files to you via email. But then to reproduce, simply run normal commands to get the db synced with the project.yaml changes.
1. `composer install`
2. `./craft migrate/all` (you can skip this actually, since there are no migrations to run)
3. `./craft project-config/sync`

You'll see the error message in the terminal. Go to your logs/console.log to find the full error.

### Expected behaviour
No error.

### Screenshots
Here's the `seoOverride` field noted in the log.
<img src="https://user-images.githubusercontent.com/984311/87665323-bd841c00-c734-11ea-975e-fabdeb1b5b59.png" width="350">

### Versions
- Plugin version: 3.3.8 (both in the db and composer)
- Craft version: 3.4.25 (both in the db and composer)

**Comment by khalwat** [comment]
It's apparently looking for a field with the handle `seoOverride` which doesn't exist. How it could get into this state, I don't know, but I put in additional checks in https://github.com/nystudio107/craft-seomatic/commit/2b9e42f1617db2ba85406babd0b3cdd7a3e3e746

Set your semver to `dev-develop` to test the fix, and lmk!

**Comment by sjcallender** [comment]
> It's apparently looking for a field with the handle `seoOverride` which doesn't exist.

Hmm. That field does exist. I'm testing the `dev-develop` version now though and will report back.

**Comment by sjcallender** [comment]
Ran with `dev-develop` f5b1f15 and no errors. Thanks Andrew.
