### ISSUE TITLE
TypeError after disabling the base URL for a site

### ISSUE THREAD

**Issue by OscarBarrett** [nystudio107/craft-seomatic#752]
### Describe the bug
Brand new installation with a single site and no changes made to SEOmatic, disabling the base URL for a site results in the Craft CP constantly crashing.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Settings -> Sites
2. Edit the site, untick "This site has its own base URL" and save
3. See error message `Argument 1 passed to craft\helpers\UrlHelper::stripQueryString() must be of the type string, null given, called in /app/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php on line 440` on every following CP request. Recoverable by reverting the project config file change to the site and re-applying the project config.

Project config change looks like this:
```diff
-baseUrl: 'http://$PRIMARY_SITE_URL'
+baseUrl: null
 enabled: true
 handle: default
-hasUrls: true
+hasUrls: false
 language: en-AU
 name: Craft
 primary: true

```

Stack trace:
```bash
TypeError: Argument 1 passed to craft\helpers\UrlHelper::stripQueryString() must be of the type string, null given, called in /app/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php on line 440 and defined in /app/vendor/craftcms/cms/src/helpers/UrlHelper.php:366
Stack trace:
#0 /app/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(440): craft\helpers\UrlHelper::stripQueryString(NULL)
#1 /app/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(280): nystudio107\seomatic\helpers\DynamicMeta::addMetaJsonLdBreadCrumbs(1)
#2 /app/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(228): nystudio107\seomatic\helpers\DynamicMeta::addDynamicMetaToContainers('settings/sites', 1)
#3 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\redis\Cache))
#4 /app/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\redis\Cache))
#5 /app/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(219): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 1, Object(yii\caching\TagDependency))
#6 /app/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(53): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('settings/sites', 1)
#7 /app/vendor/twig/twig/src/ExtensionSet.php(329): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#8 /app/vendor/twig/twig/src/Environment.php(928): Twig\ExtensionSet->getGlobals()
#9 /app/vendor/twig/twig/src/Environment.php(948): Twig\Environment->getGlobals()
#10 /app/vendor/twig/twig/src/Template.php(378): Twig\Environment->mergeGlobals(Array)
#11 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#12 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /app/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render('settings/sites/...', Array)
#15 /app/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate('settings/sites/...', Array)
#16 /app/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate('settings/sites/...', Array, 'cp')
#17 /app/vendor/craftcms/cms/src/controllers/SitesController.php(87): craft\web\Controller->renderTemplate('settings/sites/...', Array)
#18 [internal function]: craft\controllers\SitesController->actionSettingsIndex(NULL)
#19 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#21 /app/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('settings-index', Array)
#22 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('settings-index', Array)
#23 /app/vendor/craftcms/cms/src/web/Application.php(280): yii\base\Module->runAction('sites/settings-...', Array)
#24 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('sites/settings-...', Array)
#25 /app/vendor/craftcms/cms/src/web/Application.php(265): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /app/web/index.php(21): yii\base\Application->run()
#28 {main}
```

### Versions
- Plugin version: 3.3.18
- Craft version: 3.5.10.1

**Comment by OscarBarrett** [comment]
It appears that adding non-primary sites with the base URL setting disabled is fine.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f94150506fbe6efe77363367db081bf65b4c13f7
