### ISSUE TITLE
Category sitemaps throwing 500 error

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#80]
When I attempt to visit a sitemap for any of our category groups I get the following exception:

```
2018-04-18 10:23:51 [172.19.0.1][-][-][error][TypeError] TypeError: Argument 1 passed to craft\helpers\UrlHelper::siteUrl() must be of the type string, null given, called in /var
/www/html/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php on line 182 and defined in /var/www/html/vendor/craftcms/cms/src/helpers/UrlHelper.php:210
Stack trace:
#0 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php(182): craft\helpers\UrlHelper::siteUrl(NULL, NULL, NULL, 1)
#1 [internal function]: nystudio107\seomatic\models\SitemapTemplate->nystudio107\seomatic\models\{closure}(Object(yii\redis\Cache))
#2 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\redis\Cache))
#3 /var/www/html/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php(308): yii\caching\Cache->getOrSet('seomatic_sitema...', Object(Closure), 30, Object(yii\caching\
TagDependency))
#4 /var/www/html/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php(144): nystudio107\seomatic\models\SitemapTemplate->render(Array)
#5 /var/www/html/vendor/nystudio107/craft-seomatic/src/controllers/SitemapController.php(80): nystudio107\seomatic\services\Sitemaps->renderTemplate('SeomaticSitemap...', Array)
#6 [internal function]: nystudio107\seomatic\controllers\SitemapController->actionSitemap(1, 'categorygroup', 'recipeCategorie...', 1)
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('sitemap', Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('sitemap', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(238): yii\base\Module->runAction('seomatic/sitema...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seomatic/sitema...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(227): yii\web\Application->handleRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/public/index.php(21): yii\base\Application->run()
#16 {main}
```

First noticed it with `3.0.0-beta.21`, but seeing it with `3.0.0` as well.

**Comment by khalwat** [comment]
Great, thanks for the report, I'll get it taken care of.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6999bf51ca5330e1e6ad48a57cba3af128c919ba
