### ISSUE TITLE
In version 3.3.36: TypeError: Argument 1 passed to nystudio107\seomatic\helpers\UrlHelper::urlHasSubDir() must be of the type string, null given

### ISSUE THREAD

**Issue by pelmered** [nystudio107/craft-seomatic#861]
### Describe the bug
I get this error after upgrading from `3.3.35` to `3.3.36`. Downgrading back to `3.3.35` solves the problem. 

```
TypeError: Argument 1 passed to nystudio107\seomatic\helpers\UrlHelper::urlHasSubDir() must be of the type string, null given, called in *PATH*/vendor/nystudio107/craft-seomatic/src/services/FrontendTemplates.php on line 91 and defined in *PATH*/vendor/nystudio107/craft-seomatic/src/helpers/UrlHelper.php:142
Stack trace:
#0 *PATH*/vendor/nystudio107/craft-seomatic/src/services/FrontendTemplates.php(91): nystudio107\seomatic\helpers\UrlHelper::urlHasSubDir(NULL)
#1 *PATH*/vendor/nystudio107/craft-seomatic/src/Seomatic.php(764): nystudio107\seomatic\services\FrontendTemplates->loadFrontendTemplateContainers()
#2 *PATH*/vendor/nystudio107/craft-seomatic/src/Seomatic.php(490): nystudio107\seomatic\Seomatic->installCpEventListeners()
#3 *PATH*/vendor/nystudio107/craft-seomatic/src/Seomatic.php(303): nystudio107\seomatic\Seomatic->installEventListeners()
#4 *PATH*/vendor/yiisoft/yii2/base/BaseObject.php(109): nystudio107\seomatic\Seomatic->init()
#5 *PATH*/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#6 *PATH*/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('seomatic', Object(craft\web\Application), Array)
#7 *PATH*/vendor/nystudio107/craft-seomatic/src/Seomatic.php(233): craft\base\Plugin->__construct('seomatic', Object(craft\web\Application), Array)
#8 [internal function]: nystudio107\seomatic\Seomatic->__construct('seomatic', Object(craft\web\Application), Array)
#9 *PATH*/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#10 *PATH*/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('nystudio107\\seo...', Array, Array)
#11 *PATH*/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('nystudio107\\seo...', Array, Array)
#12 *PATH*/vendor/craftcms/cms/src/services/Plugins.php(934): yii\BaseYii::createObject(Array, Array)
#13 *PATH*/vendor/craftcms/cms/src/services/Plugins.php(233): craft\services\Plugins->createPlugin('seomatic', Array)
#14 *PATH*/vendor/craftcms/cms/src/base/ApplicationTrait.php(1442): craft\services\Plugins->loadPlugins()
#15 *PATH*/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#16 *PATH*/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 *PATH*/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 *PATH*/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#20 *PATH*/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 *PATH*/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 *PATH*/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#23 *PATH*/vendor/craftcms/cms/bootstrap/web.php(51): require('/application/fi...')
#24 *PATH*/web/index.php(21): require('/application/fi...')
#25 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. Update seomatic to `3.3.36` with composer.
2. Go to any craft admin page

### Expected behaviour
It should not show this error and break the craft admin. 

### Versions
- Plugin version: `3.3.36`
- Craft version: `3.6.11.2`

**Comment by khalwat** [comment]
I can fix this error, but it's being thrown because you have a Site that has `null` for a Base URL -- which probably isn't what you want.

**Comment by pelmered** [comment]
Thanks for the quick reply!

Yes, we have a default site that we didn't have a Base URL for. Setting that fixed the problem. Thank you!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/f8ce6fe6200119189765f6923a054deb0d2c358d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.37",
```
Then do a `composer clear-cache && composer update`

**Comment by pelmered** [comment]
@khalwat Yes, I removed the site URL again and updated to `dev-develop` and it still works. Good job!

I'm very impressed with the responsiveness here, thanks!

**Comment by khalwat** [comment]
Thanks! It'll be released shortly.
