### ISSUE TITLE
After running composer update SEOMatic is throwing a syntax error bug.

### ISSUE THREAD

**Issue by michtio** [nystudio107/craft-seomatic#884]
### Describe the bug

The bug occurred after running a composer update, downgrading to previous version doesn't solve the issue.
SEOMatic used to work perfectly on Craft CMS `3.6.12` - upgrade to Craft CMS `3.6.13` and the error started occurring.

It makes it impossible to see the front-end and impossible to get back-end access.

I've pinned it down to actually being SEOMatic, CLI commands still work so running:

`./craft plugin/uninstall seomatic` will remove seomatic and I can access the front-end templates and the CP again without errors.

When running `./craft plugin/install seomatic` the error returns.

See stacktrace:

```
yii\base\InvalidArgumentException: Syntax error. in /var/www/project/cms/vendor/yiisoft/yii2/helpers/BaseJson.php:133
Stack trace:
#0 /var/www/project/cms/vendor/yiisoft/yii2/helpers/BaseJson.php(107): yii\helpers\BaseJson::handleJsonError(4)
#1 /var/www/project/cms/vendor/craftcms/cms/src/helpers/Json.php(42): yii\helpers\BaseJson::decode('1.0.55', true)
#2 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(164): craft\helpers\Json::decodeIfJson('1.0.55')
#3 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(144): nystudio107\seomatic\models\MetaBundle->normalizeMetaBundleData(false)
#4 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(122): nystudio107\seomatic\models\MetaBundle::create(Array, false)
#5 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/services/FrontendTemplates.php(86): nystudio107\seomatic\services\MetaBundles->getGlobalMetaBundle(2, false)
#6 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/Seomatic.php(736): nystudio107\seomatic\services\FrontendTemplates->loadFrontendTemplateContainers()
#7 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/Seomatic.php(489): nystudio107\seomatic\Seomatic->installSiteEventListeners()
#8 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/Seomatic.php(314): nystudio107\seomatic\Seomatic->installEventListeners()
#9 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): nystudio107\seomatic\Seomatic->init()
#10 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#11 /var/www/project/cms/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('seomatic', Object(craft\web\Application), Array)
#12 /var/www/project/cms/vendor/nystudio107/craft-seomatic/src/Seomatic.php(244): craft\base\Plugin->__construct('seomatic', Object(craft\web\Application), Array)
#13 [internal function]: nystudio107\seomatic\Seomatic->__construct('seomatic', Object(craft\web\Application), Array)
#14 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#15 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('nystudio107\\seo...', Array, Array)
#16 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('nystudio107\\seo...', Array, Array)
#17 /var/www/project/cms/vendor/craftcms/cms/src/services/Plugins.php(934): yii\BaseYii::createObject(Array, Array)
#18 /var/www/project/cms/vendor/craftcms/cms/src/services/Plugins.php(233): craft\services\Plugins->createPlugin('seomatic', Array)
#19 /var/www/project/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1442): craft\services\Plugins->loadPlugins()
#20 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#21 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#22 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#23 [internal function]: yii\base\Application->__construct(Array)
#24 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#25 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#26 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#27 /var/www/project/cms/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#28 /var/www/project/cms/vendor/craftcms/cms/bootstrap/web.php(51): require('/var/www/projec...')
#29 /var/www/project/cms/web/index.php(20): require('/var/www/projec...')
#30 {main}
```

### To reproduce
Steps to reproduce the behaviour:
As described above this occurred when running a composer update to the latest Craft Version.

### Expected behaviour
Not having an error 🐛 

### Versions
- Plugin version: 3.3.40
- Craft version: 3.6.13

**Comment by khalwat** [comment]
The error you're seeing doesn't make a whole lot of sense:

```php
    public static function decodeIfJson($str, bool $asArray = true)
    {
        try {
            return static::decode($str, $asArray);
        } catch (InvalidArgumentException $e) {
            // Wasn't JSON
            return $str;
        }
    }
```

It catches that error gracefully ^

I looked over the Craft 3.6.13 changelog and didn't see anything obviously related: https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#3613---2021-05-04

Can you try nuking `vendor/` and re-installing?

**Comment by michtio** [comment]
This is resolved by spinning up/down docker.
