### ISSUE TITLE
Calling unknown method: yii\web\UrlManager::getMatchedElement()

### ISSUE THREAD

**Issue by matevisky** [nystudio107/craft-seomatic#89]
Having a strange error, when I am trying to save the element from console, which has a SEO field, with a custom URL, guess something went south with the new validation:

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\web\UrlManager::getMatchedElement()'

in /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /Users/matevisky/Documents/www/tr3nds/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(621): yii\base\Component->__call('getMatchedEleme...', Array)
#1 /Users/matevisky/Documents/www/tr3nds/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(116): nystudio107\seomatic\services\MetaContainers->setMatchedElement('', 1)
#2 /Users/matevisky/Documents/www/tr3nds/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('/', NULL)
#3 /Users/matevisky/Documents/www/tr3nds/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#4 /Users/matevisky/Documents/www/tr3nds/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#5 /Users/matevisky/Documents/www/tr3nds/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#6 /Users/matevisky/Documents/www/tr3nds/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#7 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#8 /Users/matevisky/Documents/www/tr3nds/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#9 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/web/View.php(477): Twig_Template->render(Array)
#10 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/helpers/ElementHelper.php(190): craft\web\View->renderObjectTemplate('stories/{{objec...', Object(stdClass))
#11 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/helpers/ElementHelper.php(66): craft\helpers\ElementHelper::doesUriFormatHaveSlugTag('stories/{slug}')
#12 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/validators/ElementUriValidator.php(49): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#13 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/validators/Validator.php(267): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#14 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#15 /Users/matevisky/Documents/www/tr3nds/vendor/craftcms/cms/src/services/Elements.php(377): yii\base\Model->validate()
#16 /Users/matevisky/Documents/craftplugin/src/console/controllers/ImportFileController.php(305): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#17 /Users/matevisky/Documents/craftplugin/src/console/controllers/ImportFileController.php(96): trendspublishing\craftplugin\console\controllers\ImportFileController->saveOrUpdateArticle(Array, Object(Tightenco\Collect\Support\Collection))
#18 [internal function]: trendspublishing\craftplugin\console\controllers\ImportFileController->actionIndex(0)
#19 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('index', Array)
#22 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('index', Array)
#23 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('craftplugin/imp...', Array)
#24 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('craftplugin/imp...', Array)
#25 /Users/matevisky/Documents/www/tr3nds/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /Users/matevisky/Documents/www/tr3nds/craft(22): yii\base\Application->run()
#27 {main}

```

It is a cloudanry based file system, and I am using this custom URL:
https://res.cloudinary.com/XXX/image/upload/w_1200,h_630,c_thumb/{entry.headerImage.one().filename}

On the CP I am able to save the record, it is only happening from console app:
```
        $result = Craft::$app->elements->saveElement($article);
```

**Comment by matevisky** [comment]
3.0.2 version is working fine

**Comment by khalwat** [comment]
Looks like Craft doesn't install its own URL manager for console requests. I'll have a fix for you shortly.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/82b2e8d07e60cbf9c90ecb63cb4631bb1683b9d0
