### ISSUE TITLE
SEOMatic migration fails

### ISSUE THREAD

**Issue by Timusan** [nystudio107/craft-seomatic#914]
### Describe the bug
Upgrading from SEOMatic 3.3.42 to 3.3.43 fails at migration step `m210603_213100_add_gql_schema_components`

```
*** applying m210603_213100_add_gql_schema_components
Exception: Undefined array key "name" (*****/vendor/craftcms/cms/src/services/Gql.php:1049)
#0 *****/vendor/craftcms/cms/src/services/Gql.php(1049): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '****...', 1049)
#1 *****/vendor/craftcms/cms/src/base/ApplicationTrait.php(1664): craft\services\Gql->handleChangedSchema(Object(craft\events\ConfigEvent))
#2 *****/vendor/craftcms/cms/src/services/ProjectConfig.php(1185): craft\console\Application->craft\base\{closure}(Object(craft\events\ConfigEvent))
#3 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#4 *****/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#5 *****/vendor/craftcms/cms/src/services/ProjectConfig.php(748): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#6 *****/vendor/craftcms/cms/src/services/ProjectConfig.php(1175): craft\services\ProjectConfig->_processConfigChangesInternal('graphql.schemas...')
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#8 *****/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(craft\events\ConfigEvent))
#9 *****/vendor/craftcms/cms/src/services/ProjectConfig.php(748): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#10 *****/vendor/craftcms/cms/src/services/ProjectConfig.php(517): craft\services\ProjectConfig->_processConfigChangesInternal('graphql.schemas...', true, NULL)
#11 *****/vendor/nystudio107/craft-seomatic/src/migrations/m210603_213100_add_gql_schema_components.php(28): craft\services\ProjectConfig->set('graphql.schemas...', Array)
#12 *****/vendor/craftcms/cms/src/db/Migration.php(52): nystudio107\seomatic\migrations\m210603_213100_add_gql_schema_components->safeUp()
#13 *****/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): craft\db\Migration->up()
#14 *****/vendor/craftcms/cms/src/console/controllers/MigrateController.php(374): yii\console\controllers\BaseMigrateController->migrateUp('m210603_213100_...')
#15 [internal function]: craft\console\controllers\MigrateController->actionAll()
#16 *****/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 *****/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#18 *****/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#19 *****/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#20 *****/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#21 *****/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#22 *****/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#23 *****/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#24 *****/craft(27): yii\base\Application->run()
#25 {main}
*** failed to apply m210603_213100_add_gql_schema_components (time: 0.041s)
```

### Versions
- Plugin version: 3.3.42 (upgrade to 3.3.43)
- Craft version: Tried on both  3.6.15 and  3.6.17

**Comment by khalwat** [comment]
Is this a Craft Pro or Craft Solo license? It shouldn't matter I don't think, but just to get that data...

**Comment by Timusan** [comment]
This is on a Craft Pro license.

**Comment by khalwat** [comment]
I've tested this, and I'm unable to reproduce it.

This seems like it might be a workflow thing -- are you applying the migrations in local dev, and then pushing the changed Project Config files up to production?

**Comment by khalwat** [comment]
Related to https://github.com/nystudio107/craft-seomatic/issues/920

**Comment by khalwat** [comment]
I believe this is actually a Project Config issue: https://github.com/craftcms/cms/issues/7795#issuecomment-871704218

**Comment by theskyfloor** [comment]
Just ran into this and it tanked my install. Wasn't running a push from dev to production. Was simply updating on dev.

**Comment by khalwat** [comment]
@theskyfloor pretty sure this isn't an issue with SEOmatic or the migration FWIW -- I think it's Project Config related. Have you seen the thread I linked to?

**Comment by theskyfloor** [comment]
I did but I thought it wasn't related because I am not using project config, although you are right, perhaps the same issue is popping up there. Oddly enough when I restored my database to the pre-update version, everything worked as expected and I am not up to date. Thanks for the reply!

**Comment by khalwat** [comment]
Well, what version of Craft are you using? Project Config is always on / in use regardless after I believe Craft 3.4
