### ISSUE TITLE
Ajax-submitted front-end forms throw 404s related to SitemapTemplate.php

### ISSUE THREAD

**Issue by louderthan10** [nystudio107/craft-seomatic#951]
### Describe the bug
This was a weird one to figure out, but I think it has to do with SEOmatic. When I submit a front-end entry form (`entries/save-entry` or `guest-entries/save` actions) via ajax, the form returns a 404 error to the user (though the form data is successfully submitted and the entry is created or edited).

If I disable SEOmatic, the form submits without errors.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "https://louderthanten.com/training/enrol?program=dpm-foundations"
2. Fill out the form
3. See error message "Request failed with status code 404" (even though the form actually submits successfully)

### Expected behaviour
The form submits without an error.

### Stack trace
```
yii\web\NotFoundHttpException: Page not found. in [...]/vendor/nystudio107/craft-seomatic/src/models/SitemapTemplate.php:135 Stack trace: 
#0 [...]/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php(538): nystudio107\seomatic\models\SitemapTemplate->render(Array) 
#1 [...]/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(455): nystudio107\seomatic\services\Sitemaps->invalidateSitemapCache('applications', 2, 'section') 
#2[...]/vendor/nystudio107/craft-seomatic/src/Seomatic.php(612): nystudio107\seomatic\services\MetaBundles->invalidateMetaBundleByElement(Object(craft\elements\Entry), true) 
#3 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(craft\events\ElementEvent))
#4 [...]/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent)) 
#5 [...]/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent)) 
#6 [...]/vendor/craftcms/cms/src/services/Elements.php(2780): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent)) 
#7 [...]/vendor/craftcms/cms/src/services/Elements.php(773): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true) 
#8 [...]/vendor/craftcms/guest-entries/src/controllers/SaveController.php(137): craft\services\Elements->saveElement(Object(craft\elements\Entry)) 
#9 [internal function]: craft\guestentries\controllers\SaveController->actionIndex() 
#10 [...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#11 [...]/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) 
#12 [...]/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('', Array) 
#13 [...]/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('', Array) 
#14 [...]/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('guest-entries/s...', Array)
#15 [...]/vendor/craftcms/cms/src/web/Application.php(589): craft\web\Application->runAction('guest-entries/s...', Array) 
#16 [...]/vendor/craftcms/cms/src/web/Application.php(255): craft\web\Application->_processActionRequest(Object(craft\web\Request)) 
#17 [...]/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request)) 
#18 [...]/index.php(21): yii\base\Application->run() 
#19 {main}
```

### Versions
- Plugin version: 3.3.48 & 3.4.0
- Craft version: 3.7.9

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/846129cfb1a708cecd41b9b90da3fc5c0f4e631c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.1”,
```
Then do a `composer clear-cache && composer update`

**Comment by louderthan10** [comment]
Confirmed, it works now. Thanks for the quick fix, bud!
