### ISSUE TITLE
Exceptions after latest update

### ISSUE THREAD

**Issue by bossanova808** [nystudio107/craft-seomatic#986]
### Describe the bug

Hey fella - I am suddenly getting Rollbar reports of exceptions, specifcally on paginated pages, with the latest SEOMatic.  Everything is (very long since) set up (100% in your report thingy) and have not any vaguely related changes for a long time now.

From this line (curious spelling here...)

` $cuurentPaginationUrl = Seomatic::$seomaticVariable->meta->canonicalUrl;`

Trace:

```
 PHP Notice – yii\base\ErrorException
Trying to get property 'canonicalUrl' of non-object

    1. in /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php at line 533
    524525526527528529530531532533534535536537538539540541542

         * @param string   $uri
         * @param int|null $siteId
         */
        public static function addMetaLinkHrefLang(string $uri = null, int $siteId = null)
        {
            Craft::beginProfile('DynamicMeta::addMetaLinkHrefLang', __METHOD__);
            $siteLocalizedUrls = self::getLocalizedUrls($uri, $siteId);
            $cuurentPaginationUrl = null;
            if (Seomatic::$plugin->metaContainers->paginationPage !== '1') {
                $cuurentPaginationUrl = Seomatic::$seomaticVariable->meta->canonicalUrl;
            }
            if (!empty($siteLocalizedUrls)) {
                // Add the rel=alternate tag
                $metaTag = Seomatic::$plugin->link->create([
                    'rel' => 'alternate',
                    'hreflang' => [],
                    'href' => [],
                ]);
                // Add the alternate language link rel's
```

### To reproduce
I don't think I am doing anything too odd here - it's just paginated results of

N.b. Exception only happens _after_ the first page

```
{# Filtering by year .... #}
{% elseif craft.app.request.getSegment(2)=="year" %}
	{% set year = craft.app.request.getSegment(3) %}
	{% if not year|length %}
    	{% exit 404 %}
	{% endif %}
	{% set blogs = craft.entries.section('blog').after(year).before(year+1).limit(itemsOnPage).with(['masterImage','blogCategory']) %}
    {% if not blogs|length %}
        {% exit 404 %}
    {% endif %}
```

### Expected behaviour

No exceptions ;)

More trace:

```
yii\base\ErrorException: Trying to get property 'canonicalUrl' of non-object in /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php:533
Stack trace:
#0 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError()
#1 /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(533): craft\web\ErrorHandler->handleError()
#2 /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php(300): nystudio107\seomatic\helpers\DynamicMeta::addMetaLinkHrefLang()
#3 /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(247): nystudio107\seomatic\helpers\DynamicMeta::addDynamicMetaToContainers()
#4 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}()
#5 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func()
#6 /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(238): yii\caching\Cache->getOrSet()
#7 /var/www/vhosts/c3-dev/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(54): nystudio107\seomatic\services\MetaContainers->loadMetaContainers()
#8 /var/www/vhosts/c3-dev/vendor/twig/twig/src/ExtensionSet.php(329): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#9 /var/www/vhosts/c3-dev/vendor/twig/twig/src/Environment.php(928): Twig\ExtensionSet->getGlobals()
#10 /var/www/vhosts/c3-dev/vendor/twig/twig/src/Environment.php(948): Twig\Environment->getGlobals()
#11 /var/www/vhosts/c3-dev/vendor/twig/twig/src/Template.php(378): Twig\Environment->mergeGlobals()
#12 /var/www/vhosts/c3-dev/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#13 /var/www/vhosts/c3-dev/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#14 /var/www/vhosts/c3-dev/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#15 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#16 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#17 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate()
#18 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate()
#19 [internal function]: craft\controllers\TemplatesController->actionRender()
#20 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#21 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#22 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#23 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#24 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction()
#25 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#26 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest()
#27 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#28 /var/www/vhosts/c3-dev/web/index.php(21): yii\base\Application->run()
#29 {main}
```

Let me know if I can help you with more info...

**Comment by bossanova808** [comment]
(downgrading to 3.4.10 fixes things for now...)

**Comment by khalwat** [comment]
I'm guessing you're not using `{% do seomatic.helper.paginate() %}`? https://nystudio107.com/docs/seomatic/using.html#helper-functions-seomatic-helper

I'm a little confused because the error implies that `Seomatic::$seomaticVariable->meta` is `null` at this point, which seems not possible...

In any event, this should be addressed in: https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.13

**Comment by bossanova808** [comment]
Actually I was using it, but I tried 3.4.11 both with and without that - and got the same exception either way.  I did think it was odd that `meta` was null at that point.  But I checked the page source and e.g. the JSON-LD was present and correct...

In a nutshell for these index pages (the entries query varies depending on section/page but is basically the same...)all I do is this:

```
{% set blogs = craft.entries.section('blog').limit(itemsOnPage).with(['masterImage','blogCategory']) %}
{# Paginate the results #}
{% paginate blogs as pageInfo, blogs %}
{% do seomatic.helper.paginate(pageInfo) %}
# SEO Title is page title plus subtitle #}
{% if subTitle %}
	{% set seoTitle = subTitle ~  " - Blog Index" %}
{%  else %}
	{% set seoTitle = "The Image Science Blog" %}
{% endif %}
{% do seomatic.meta.setAttributes({
	"seoTitle": seoTitle,
	"seoDescription": seoTitle
	})
%}
```

In any case, I have updated to 3.4.13 just now and the exception is gone, thanks....and the JSON-LD etc is there too.  

Hope you are well and safe/sane mate!

**Comment by khalwat** [comment]
Fantastic! Same same J! :)
